### ISSUE TITLE
detailed-query page missing some lines from table

### ISSUE THREAD

**Issue by klensy** [rust-lang/rustc-perf#1022]
https://perf.rust-lang.org/detailed-query.html?sort_idx=12&commit=635ba4d6ff55c13d3f40dd9b82d773d172377606&base_commit=60e70cc909f84e84ed3bca3fe3459ddceefdd08c&benchmark=await-call-tree-debug&run_name=incr-full

`Executions delta: -35319.000` total
And only two rows with non zero values
```
2795 | -7064.000  (-71.7%)
2880 | -7064.000  (-71.0%)
```
So sum of rows didn't equal total.

Similar example here: https://perf.rust-lang.org/detailed-query.html?commit=635ba4d6ff55c13d3f40dd9b82d773d172377606&base_commit=60e70cc909f84e84ed3bca3fe3459ddceefdd08c&benchmark=await-call-tree-debug&run_name=full

total: -14127 and zero non zero lines
P.S. executions delta column should be integer type.

**Comment by tgnottingham** [comment]
This is happening because some queries, e.g. `item_children`, only exist in the profile which we're comparing against. We're not showing lines for such queries in the table, but we're still including their counts in the executions delta. I think it would make sense to show these lines.

**Comment by tgnottingham** [comment]
I've got a fix in the works that I can probably post tomorrow, unless someone is already on top of it.
