### ISSUE TITLE
benchmark results not filtered out, even if %change= 0%

### ISSUE THREAD

**Issue by klensy** [rust-lang/rustc-perf#1067]
Latest perf runs `webrender-wrench-debug` isn't filtered out with given settings, if selected `max-rss` metric.
It should be filtered out: change = 0 and it isn't significant.

for example:
https://perf.rust-lang.org/compare.html?start=15491d7b6be1065217e09bd735e4ecffbe9838ba&end=bc8ad24020a160e1acd7ac9f7671947dcc01264c&stat=max-rss
https://perf.rust-lang.org/compare.html?start=bb918d0a5bf22211df0423f7474e4e4056978007&end=15491d7b6be1065217e09bd735e4ecffbe9838ba&stat=max-rss
https://perf.rust-lang.org/compare.html?start=485ced56b8753ec86936903f2a8c95e9be8996a1&end=2ee06e737208ce1bd1c18df5ea3aba733e6ac2a7&stat=max-rss
![pic1](https://user-images.githubusercontent.com/1782831/136674941-6bbcb7f8-a636-4450-81ab-fcca39b74047.png)

Perhaps there some issues with given benchmark?

**Comment by Kobzol** [comment]
Fixed by https://github.com/rust-lang/rustc-perf/pull/1421.
