### ISSUE TITLE
massive benchmark panics: thread 'main' panicked at 'couldn't read string_data file: Os { code: 2, kind: NotFound, message: "No such file or directory" }

### ISSUE THREAD

**Issue by klensy** [rust-lang/rustc-perf#1075]
A lot of benches failed, as can be seen at https://perf.rust-lang.org/status.html (at least now) with errors like:
```
thread 'main' panicked at 'couldn't read string_data file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', analyzeme/src/profiling_data.rs:50:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: "Error reading top-level stream in file `rust_grammar-12029.mm_profdata`: Expected file format version 7 but found `8`"
thread 'main' panicked at 'failed to run summarize and summarize-9.0. Errors:
summarize: failed to run summarize in "/tmp/.tmp1Gpe86/self-profile-output" with prefix "rust_grammar-12029.mm_profdata"
summarize-9.0: failed to run summarize-9.0 in "/tmp/.tmp1Gpe86/self-profile-output" with prefix "rust_grammar-12029.mm_profdata"', collector/src/rustc-fake.rs:373:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: `rust-grammar` (lib) generated 5 warnings
error: could not compile `rust-grammar`; 5 warnings emitted
```

But perf run didn't have any warning about that fail in report at PR https://github.com/rust-lang/rust/pull/90067 or compare page https://perf.rust-lang.org/compare.html?start=1af55d19c7a9189374d89472f97dc119659bb67e&end=42983a28ab3c70728da7a9b932b667c978dd898d, it simply silently skips failed benches.

**Comment by klensy** [comment]
Rerun for https://github.com/rust-lang/rust/pull/89100 failed: https://perf.rust-lang.org/compare.html?start=42983a28ab3c70728da7a9b932b667c978dd898d&end=6162529a01473bbb2427fa27354cbafc3c514eee

**Comment by Mark-Simulacrum** [comment]
Closing as fixed, we're tracking the bad error reporting in #1062.
