### ISSUE TITLE
Why do we use cachegrind for instruction counts?

### ISSUE THREAD

**Issue by In-line** [rust-lang/rustc-perf#1107]
Why do we use cachegrind for instruction counts, cycles, etc.. ?

I see that perf can report instructions with `perf record -e instructions`. 
In our proprietary codebase tests, perf is noticeably faster than cachegrind.

**Comment by Mark-Simulacrum** [comment]
cachegrind is much less noisy, in general.

The perf.rust-lang.org data is collected with perf stat, though, not cachegrind, precisely because perf is faster.

I'm not sure this answers your question though -- what do you mean by using cachegrind for instruction count + cycles?

**Comment by In-line** [comment]
I see, thank you. From reading source code, I incorrectly assumed that main profiler was cachegrind, instead of perf.
