### ISSUE TITLE
Bootstrap timings no longer shown on comparison pages

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rustc-perf#1117]

**Comment by Mark-Simulacrum** [comment]
bootstrap builds are currently broken -- see https://perf.rust-lang.org/status.html

I suspect this'll get fixed by https://github.com/rust-lang/rust/pull/91720

**Comment by bjorn3** [comment]
Fixed by rust-lang/rust#91720. Still might be nice to show a message if either side of the comparison doesn't have bootstrap timings.

**Comment by Mark-Simulacrum** [comment]
Yeah, that's https://github.com/rust-lang/rustc-perf/issues/1062.
