### ISSUE TITLE
Add minimized version of projection caching example

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rustc-perf#1124]
In https://github.com/rust-lang/rust/pull/89831#issuecomment-941930652, a build went from taking 3 minutes to 12 **hours**. Nothing in our current benchmark suite reflected this regressions (and the fix showed "This benchmark run did not return any relevant changes."). We should add a reduced version of that example which captures the enormous impact of projection cache 'completion' on certain workloads.

**Comment by Mark-Simulacrum** [comment]
Do we have any example code for that case yet? I definitely agree that we should add something to this effect to the benchmark suite, whether as a real-world test case or a manufactured stress test.

**Comment by Aaron1011** [comment]
I don't know if we have a concrete example. @nayato: Are you able to share the codebase that experienced the regression you described in https://github.com/rust-lang/rust/pull/89831#issuecomment-941930652?
