### ISSUE TITLE
Detailed comparison view broken

### ISSUE THREAD

**Issue by nikic** [rust-lang/rustc-perf#1150]
For example: https://perf.rust-lang.org/detailed-query.html?commit=7531d2fdd49966d83830a7b4596c95587b1e9573&base_commit=e4ff9031acdb3579f61a67ded2cf0faa00bea3fc&benchmark=diesel-check&scenario=incr-unchanged

This throws an alert with 502 bad gateway, and no data in the table.

**Comment by Mark-Simulacrum** [comment]
Investigating -- looks like the panic comes from https://github.com/rust-lang/rustc-perf/blob/d676bcf0528dc43a8c1eb6f3eab55db6a6549277/site/src/request_handlers/self_profile.rs#L718
