### ISSUE TITLE
Improve perf.rlo frontend experience

### ISSUE THREAD

**Issue by rylev** [rust-lang/rustc-perf#1184]
In https://github.com/rust-lang/rustc-perf/pull/1181 @Kobzol mentions that we are at the limit of even what Vue2 can offer us on the compare page. This is despite the fact that most other pages on the compare site are built by concatenating HTML strings which can be very hard to understand and extend. 

I propose we do the following to improve our ability to iterate on the frontend experience:
* Update to Vue3
* Componentize common elements as Vue components
* Introduce the usage of View on all pages that have more than just basic dynamic content (e.g., perhaps everything but the help page)

**Comment by Kobzol** [comment]
The frontend now uses Vue 3, `npm`, `parcel` and `TypeScript`, and the whole frontend has been refactored and split into components. I think that this goal has been fully achieved.
