### ISSUE TITLE
Enable gzip on responses

### ISSUE THREAD

**Issue by miwig** [rust-lang/rustc-perf#1187]
The site is very slow, and much of that (>1s) seems to be network transfers, with the graphs page transferring 1.4MB and the comparison page 600kB. ce59f44351bef482a23c61d5fb1339102b71e8f3 removed gzip on responses with the comment "In prod, nginx can do this for us", but as far as I can tell it was never enabled or got disabled at some point. #742 and #745 have also previously suggested enabling gzip (and ditching MessagePack), but as far as I can tell, regardless of whether MessagePack is used, [just enabling gzip should be a compression win](https://www.peterbe.com/plog/msgpack-vs-json-with-gzip).

**Comment by Mark-Simulacrum** [comment]
Yeah, gzip probably makes sense. There's been some light work done historically on making the response itself smaller and probably more could be done there, but if we can quickly apply compression atop that will likely work well too.

**Comment by Mark-Simulacrum** [comment]
Oh, this would have to be done in-code -- we don't run with nginx in front of us and I don't think anything in our pipeline is able to do this for us right now.

**Comment by miwig** [comment]
Ah, I see... the commit message for ce59f44351bef482a23c61d5fb1339102b71e8f3 seemed to suggest this was a matter of setting an nginx config option. I will work on getting it done in code then.

**Comment by Mark-Simulacrum** [comment]
Yeah, we used to passthrough nginx but that is no longer the case.
