### ISSUE TITLE
Compare site transfers unused data (historical_statistics)

### ISSUE THREAD

**Issue by miwig** [rust-lang/rustc-perf#1200]
7e3784d6f5c923a22a63e75169a61b8b38b81cfc introduced `historical_statistics` to calculate variance, but as far as I can tell everything is calculated on the server and the client never touches this field. Meanwhile the response size increased from 110kB to 630kB, slowing down page load times.

We could

1. Make this data opt-in through a request parameter
2. Make it opt-out
3. Remove it from responses altogether

@rylev If you have a preferred solution I would be happy to make a pull request. I would lean towards 1. unless there are already other consumers of this data that would break, in which case I would suggest 2. Or did I overlook something and there's a good reason for this data to be transferred?

**Comment by Mark-Simulacrum** [comment]
I think dropping the data for now makes sense - it looks like it would be relatively easy to restore if we needed to.
