### ISSUE TITLE
no perf runs starting from #95280

### ISSUE THREAD

**Issue by klensy** [rust-lang/rustc-perf#1246]
No perf runs (results?) on merged PRs starting from [#95280](https://github.com/rust-lang/rust/pull/95280), plus queue looks broken (not empty, but without any info) https://perf.rust-lang.org/status.html

**Comment by klensy** [comment]
Currently there [issues](https://github.com/rust-lang/rust/pull/95274#issuecomment-1079758247) with crates.io, so maybe this is not fixable now.

**Comment by klensy** [comment]
Queue reanimated.

**Comment by Mark-Simulacrum** [comment]
See https://rust-lang.zulipchat.com/#narrow/stream/247081-t-compiler.2Fperformance/topic/Status.20page.20broken for context here.
