### ISSUE TITLE
If bootstrap timing partially or completely missing, indication on compare page is easy to miss

### ISSUE THREAD

**Issue by klensy** [rust-lang/rustc-perf#1297]
See the links on https://github.com/rust-lang/rust/issues/96188

**Comment by lqd** [comment]
The compare page shows that when a benchmark stops building: e.g. in this case [the summary bot mentioned](https://github.com/rust-lang/rust/pull/95906#issuecomment-1101693631) the `rustc` benchmark stopped building and [it's showing that at the top](https://perf.rust-lang.org/compare.html?start=6fd7e9010db6be7605241c39eab7c5078ee2d5bd&end=0516711ab057d9731f55511f00f9d426bc9db724) of the compare page for that run.

In the other cases, if a given run doesn't itself break a benchmark, then they are listed in [the status page](https://perf.rust-lang.org/status.html). 

Maybe we should automatically open `rust-lang/rust` issues when that happens, much like `toolstate` status changes.

**Comment by rylev** [comment]
So I guess the issue here is not that the there's no indication (there is - see below), but that the indication isn't very clear. 

![image](https://user-images.githubusercontent.com/1327285/165043860-ab910bd8-4e35-4ab8-8814-8bea393086f2.png)

**Comment by klensy** [comment]
No, about empty bootstrap timings table: for first link https://perf.rust-lang.org/compare.html?start=8305398d7ae6128811ec2b3223939bcd067530c2&end=311e2683e1bad87715b1558f7900e294d24ce491

![chrome_2022-04-25_10-52-07](https://user-images.githubusercontent.com/1782831/165044735-fb7d4fda-a6ae-474f-a23f-1ef14c441bb7.png)

Or partially empty one for second one, without clear indication, that something wrong happened in data.

But that `newly broken` not too good too.

**Comment by Kobzol** [comment]
![image](https://github.com/rust-lang/rustc-perf/assets/4539057/b61d5d6e-45e2-48e6-b3ed-d307bf95a9be)
This is how it currently looks like. I think that it's much clearer that there is a problem with bootstrap now. @klensy if you agree, feel free to close this issue.

**Comment by klensy** [comment]
Ok.
