### ISSUE TITLE
If perf run completed without any relevant results, github tag `S-waiting-on-perf` didn't removed

### ISSUE THREAD

**Issue by klensy** [rust-lang/rustc-perf#1307]
For example, https://github.com/rust-lang/rust/pull/96359 or https://github.com/rust-lang/rust/pull/96179

**Comment by Kobzol** [comment]
That might be caused by the situation described [here](https://github.com/rust-lang/rustc-perf/pull/1291#pullrequestreview-937670699)? @rylev
