### ISSUE TITLE
Additional details per metric

### ISSUE THREAD

**Issue by rylev** [rust-lang/rustc-perf#1328]
In addition to the work being discussed in #1322, it might be good to include the following additional details for each of the metrics:
* **Number of uniquely impacted benchmarks**. We currently show the number of relevant test case results, but it's also relevant to know how widespread the issue is over the total surface area of the perf suite. For example, a perf run that has 12 total relevant test case results but that impact only 1 particular benchmark can be treated differently than if 12 different benchmarks are impacted.
* **Average percent change across the entire benchmark suite**. We currently show the average percent change for the relevant test case results, but obviously a +1% change impacting 5 test cases vs a 1% change impacting 40 test case results should be treated differently. The view is now required to piece this information together themselves. 
* **Average percent change per profile**. It would be good to know if one particular profile is more impacted than others. This could simply be an extra line of detail we display when one particular profile is > 75% (or some other percentage) of the impacted test case results. 
* **Average percent change per scenario**. Same as the per profile analysis

**Comment by Kobzol** [comment]
I was thinking about this and I wonder if this all should rather be shown in the compare page? There's only so much that can fit inside the PR comments, and we have already added two new sections and tables there.

**Comment by Kobzol** [comment]
I think that with the recent dashboard changes, this can be now closed?

**Comment by rylev** [comment]
I agree!
