### ISSUE TITLE
`bench-rustc` broken after bootstrap removed from workspace

### ISSUE THREAD

**Issue by adamgemmell** [rust-lang/rustc-perf#1350]
I get this locally:

```
collector error: Failed to benchmark 'rustc', recorded: measure rustc: building rustc: expected success, got exit status: 1

stderr=error: current package believes it's in a workspace when it's not:
current:   /data_nvme0n1/rustc-perf/rust/src/bootstrap/Cargo.toml
workspace: /data_nvme0n1/rustc-perf/Cargo.toml

this may be fixable by adding `rust/src/bootstrap` to the `workspace.members` array of the manifest located at: /data_nvme0n1/rustc-perf/Cargo.toml
Alternatively, to keep it out of the workspace, add the package to the `workspace.exclude` array, or add an empty `[workspace]` table to the package's manifest.
```
https://github.com/rust-lang/rust/pull/97513 removed bootstrap from the Rust workspace and is the first master commit since the last result: https://perf.rust-lang.org/bootstrap.html

Adding the Rust checkout to `workspace.exclude` fixes it for cases where the CWD is the root of rustc-perf, as the checkout is made in the CWD. Is there a better way?

Curiously the perf run on the PR itself seems to show bootstrap timings successfully. Does that CI run have a different working directory set?

**Comment by lqd** [comment]
cc @jyn514

**Comment by adamgemmell** [comment]
Glad we arrived at the same conclusion!

**Comment by lqd** [comment]
Done. I'll close this issue once we have bootstrap timings back.

**Comment by lqd** [comment]
The [most recent run](https://perf.rust-lang.org/compare.html?start=00ebeb87ac87a492bd59ace6bd43d6ad1629ca4e&end=8e7eff8a806384acdbaeb38b2787ad4b880505d4&stat=instructions:u) has bootstrap timings back. Closing this issue.
