### ISSUE TITLE
queue not working: status page currently gives 502 status

### ISSUE THREAD

**Issue by klensy** [rust-lang/rustc-perf#1352]
https://perf.rust-lang.org/status.html don't show any current\last runs, and browser dev console shows `GET https://perf.rust-lang.org/perf/status_page 502` when page loaded.

**Comment by Mark-Simulacrum** [comment]
Fixed https://github.com/rust-lang/triagebot/commit/a2ae093f52e39cd051df4340b68a752f77464c9c -- should also be more permanently fixed now.
