### ISSUE TITLE
30-day performance chart is broken for PR commits

### ISSUE THREAD

**Issue by Kobzol** [rust-lang/rustc-perf#1354]
The values in the `Profile` column on the compare page link to a 30 day old performance chart. The start bound of the chart is calculated as (date of end bound commit - 30 days), however for PR try perf builds, the date of the end bound commit is set to 2001-01-01 for some reason (this can be seen [here](https://perf.rust-lang.org/compare.html?start=45263fc66d253f762b3880764ae48611a25bf887&end=567cf89ba17f13bc490de32582f36c7ed9c07c62&stat=instructions:u)), which [breaks](https://perf.rust-lang.org/index.html?start=2000-12-02&end=567cf89ba17f13bc490de32582f36c7ed9c07c62&benchmark=serde-1.0.136&profile=doc&scenario=full&stat=instructions:u) the chart.

The weird date probably comes from [this line](https://github.com/rust-lang/rustc-perf/blob/master/database/src/pool/postgres.rs#L1119), which uses this date if the artifact date is `None`. The date is set to `None` [here](https://github.com/rust-lang/rustc-perf/blob/master/database/src/pool/postgres.rs#L870) for try builds. I'm not sure why though - can't it be just set to the commit date? Or to "today" at the time of insertion if for some reason the date of try commits is not available?

@Mark-Simulacrum Do you recall why is it set to `None`?

**Comment by Mark-Simulacrum** [comment]
This was done as an easy way to pass around the fact that they're try commits (and not from master), which is significant in some places. It predates the postgres database. I'm not sure whether we sufficiently preserve state to avoid needing this hack today, though I would suspect that we do.

We should be careful when changing the date here to avoid displaying the commits on regular graphs, since try builds generally shouldn't show up there.

**Comment by Kobzol** [comment]
I see. I wonder though, do we need this "hack" anymore when there is the `type` column in the `artifact` table? It seems that it should be enough to distinguish try/master/release commits.

**Comment by Mark-Simulacrum** [comment]
I'm not sure if it's always available to us, but as I said, seems plausible; needs some investigation if we're going to change it.

**Comment by Kobzol** [comment]
I created https://github.com/rust-lang/rustc-perf/pull/1357, we can continue the discussion there.

**Comment by Kobzol** [comment]
Resolved by https://github.com/rust-lang/rustc-perf/pull/1357, https://github.com/rust-lang/rustc-perf/pull/1393 and https://github.com/rust-lang/rustc-perf/pull/1399.
