### ISSUE TITLE
Consider making unrolled up artifacts *only* after perf regression

### ISSUE THREAD

**Issue by rylev** [rust-lang/rustc-perf#1383]
After #1372 and follow ups, we now kick off builds for all rolled up PRs in a roll up as if they were merged directly and independently into master. This works well for our purposes but is arguably a bit of a waste of resources. We may want to consider instead waiting for perf results to come back and only kick off this process if the roll up exhibits performance regressions.

**Comment by Mark-Simulacrum** [comment]
So I think there's actually a lot of benefits modulo perf to these artifacts existing (e.g., bisection), so I'd rather we keep them at least for now. We can reconsider if there's queueing on rust-lang-ci that makes us worry, but I don't expect there to be.

**Comment by rylev** [comment]
These have proved useful enough outside of perf runs that, as @Mark-Simulacrum suggests, we should continue to always build them. Closing this issue.
