### ISSUE TITLE
compare page: unknown variant `size:crate_metadata`, expected one of ...

### ISSUE THREAD

**Issue by klensy** [rust-lang/rustc-perf#1389]
selecting crate_metadata don't work: it fails, for example https://perf.rust-lang.org/compare.html?start=34a6cae28e7013ff0e640026a8e46f315426829d&end=0459d2fa736a556332ea9613ad0edf073107cb40&stat=size%3Acrate_metadata
with error
```
Failed to deserialize request: Error("unknown variant `size:crate_metadata`, expected one of `context-switches`, `cpu-clock`, `cpu-clock:u`, `cycles:u`, `faults`, `faults:u`, `instructions:u`, `max-rss`, `task-clock`, `task-clock:u`, `wall-time`, `size:codegen_unit_size_estimate`, `size:dep_graph`, `size:linked_artifact`, `size:object_file`, `size:query_cache`, `size:work_product_index`", line: 1, column: 129
```

probably #1348 so @Kobzol ?

**Comment by Kobzol** [comment]
Thanks! We have decided to whitelist the known metrics, so if there is any unknown one, there will be a loud error. The fix is in https://github.com/rust-lang/rustc-perf/pull/1391.
