### ISSUE TITLE
GH perf bot message: number of perf builds in rollup reported by perf bot != PR's in rollup

### ISSUE THREAD

**Issue by klensy** [rust-lang/rustc-perf#1390]
https://github.com/rust-lang/rust/pull/100356 contains 8 PRs in rollup, but perf bot message talks about only one PR https://github.com/rust-lang/rust/pull/100356#issuecomment-1210363384

probably #1372 so @rylev ?

**Comment by Mark-Simulacrum** [comment]
Looks like some commits were added to the branch after merging perhaps? https://github.com/rust-lang/rust/pull/100356#commits-pushed-0a31aa2

(Cc @ehuss though I suspect GitHub may be lying about who pushed them)

I wouldn't have expected us to get the commits wrong regardless, but seems like a plausible explanation.

**Comment by ehuss** [comment]
Oh, sorry, I think I know what happened. I had rebooted my machine between two different OS's and that screws up my clock, and I forgot to resync it.  The timestamp on the commit is in the future, and GitHub seems to have placed the in-the-future time in the timeline that way.
