### ISSUE TITLE
perf runs stopped, queued 8 PRs, last run ~ 11 hours ago.

### ISSUE THREAD

**Issue by klensy** [rust-lang/rustc-perf#1430]
https://perf.rust-lang.org/status.html

`No current collection in progress. Last one finished at 8/27/2022, 2:44:43 AM local time, 10h53m35s ago.`

**Comment by Mark-Simulacrum** [comment]
Adjusted database to drop include filter which caused us to bail out too early.

cc https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/rustc-perf.20is.20stuck

**Comment by klensy** [comment]
Checked perf stream on zulip, but not infra, my bad.
