### ISSUE TITLE
Reduce variance of perf. CI machine

### ISSUE THREAD

**Issue by Kobzol** [rust-lang/rustc-perf#1450]
Currently, the machine that runs perf. benchmarks on CI uses both turbo-boost and hyper-threading. It would be nice to try to disable these features for some time (e.g. a week or two weeks). We could then observe if disabling them reduces the variance of e.g. wall-time measurements.

Experiment results:
- Hyperthreading :heavy_multiplication_x:, Turboboost :heavy_multiplication_x:
  - 2022-10-01 -> 2022-10-08, [results](https://perf.rust-lang.org/?start=2022-09-24&end=2022-10-08&kind=percentrelative&stat=wall-time) (data shown start a week before the experiment started to see the difference). Wall-time variance has been reduced substantially. CI perf. time increased by ~10%, from 1.2 to 1.3 hours. 
- Hyperthreading :heavy_check_mark:, Turboboost :heavy_multiplication_x:
  - 2022-10-08 -> 2022-10-16, [results](https://perf.rust-lang.org/?start=2022-09-24&end=2022-10-16&kind=percentrelative&stat=wall-time) (data shown from the start of the whole experiment). Wall-time variance has increased, but just slightly and on some benchmarks. The additional threads helped mostly only in `opt` builds and for large crates (e.g. `cargo`).  CI perf. time decreased only very slightly, to about 1.28 hours.
- Hyperthreading :heavy_multiplication_x:, Turboboost :heavy_check_mark:
  - 2022-10-16 -> 2022-10-22, [results](https://perf.rust-lang.org/?start=2022-09-24&end=2022-10-22&kind=percentrelative&stat=wall-time) (data shown from the start of the whole experiment). CI perf. time was about 1.25 hours.

CC @Mark-Simulacrum

**Comment by Kobzol** [comment]
Commands to do this:

# Turbo-boost
## Disable (apply)
```bash
$ sudo bash -c "echo 0 > /sys/devices/system/cpu/cpufreq/boost"
```

## Enable (revert)
```bash
$ sudo bash -c "echo 1 > /sys/devices/system/cpu/cpufreq/boost"
```

# Hyper-threading
## Disable (apply)
```bash
sudo bash -c "echo 0 > /sys/devices/system/cpu/cpu1/online"
sudo bash -c "echo 0 > /sys/devices/system/cpu/cpu3/online"
sudo bash -c "echo 0 > /sys/devices/system/cpu/cpu5/online"
sudo bash -c "echo 0 > /sys/devices/system/cpu/cpu7/online"
sudo bash -c "echo 0 > /sys/devices/system/cpu/cpu9/online"
sudo bash -c "echo 0 > /sys/devices/system/cpu/cpu11/online"
```

## Enable (revert)
```bash
sudo bash -c "echo 1 > /sys/devices/system/cpu/cpu1/online"
sudo bash -c "echo 1 > /sys/devices/system/cpu/cpu3/online"
sudo bash -c "echo 1 > /sys/devices/system/cpu/cpu5/online"
sudo bash -c "echo 1 > /sys/devices/system/cpu/cpu7/online"
sudo bash -c "echo 1 > /sys/devices/system/cpu/cpu9/online"
sudo bash -c "echo 1 > /sys/devices/system/cpu/cpu11/online"
```

**Comment by Mark-Simulacrum** [comment]
https://github.com/rust-lang/rust/commit/744e397d8855f7da87d70aa8d0bd9e0f5f0b51a1 will (hopefully) be the last commit benchmarked before I apply the changes here.

**Comment by Mark-Simulacrum** [comment]
OK, applied:

* echo 0 | sudo tee /sys/devices/system/cpu/cpufreq/boost
* echo off | sudo tee /sys/devices/system/cpu/smt/control

**Comment by the8472** [comment]
Is ASLR already disabled?

**Comment by Mark-Simulacrum** [comment]
I think so. We have kernel.randomize_va_space = 0 globally (which disables kernel ASLR), and we also run processes under set arch -R, which I believe disables ASLR (see https://github.com/rust-lang/rustc-perf/blob/572f22e4a3a9cf395534cb569aed9d3b9b8cbcb7/collector/src/bin/rustc-fake.rs#L89).

**Comment by Kobzol** [comment]
Yes, it is disabled [kernel-wise](https://github.com/rust-lang/rustc-perf/blob/master/collector/perf-runner.md) and also explicitly in [code](https://github.com/rust-lang/rustc-perf/blob/master/collector/src/bin/rustc-fake.rs#L89).

**Comment by Kobzol** [comment]
The experiment with TB and HT turned off has been concluded (I added the results to the issue description).
@Mark-Simulacrum Please change the configuration to Turbo-boost off, Hyper-threading on (so currently it should be enough to just enable Hyper-threading).

**Comment by Mark-Simulacrum** [comment]
Switched hyper-threading on. Last commit benchmarked w/o it is https://github.com/rust-lang/rust/commit/c27948d255167d827421401950c6d723ba28de8f (on master).

**Comment by Mark-Simulacrum** [comment]
Hyper-threading off, turboboost on; last commit benchmarked is rust-lang/rust@8be3ce9056d17f822704b8994f60668adf180fe8.

**Comment by Mark-Simulacrum** [comment]
https://perf.rust-lang.org/compare.html?start=bed4ad65bf7a1cef39e3d66b3670189581b3b073&end=bed4ad65bf7a1cef39e3d66b3670189581b3b073-noisy compares a single commit with "A" being turbo + hyperthreads off, and "B" being turbo and hyperthreads on.

We have left the machine with turboboost and hyperthreads both off. I think I managed to make this automatic on boot (`/etc/systemd/system/turbo-off.service` that disables both).

**Comment by tindzk** [comment]
Here are some of the experiments the Scala team has run to reduce variance of their CI machine: https://github.com/scala/scala-dev/issues/338

Stopping the `irqbalance` service could be worth looking into. This would prevent hardware interrupts from being distributed across processors.

Also, by setting the kernel parameter `nohz_full` we could reduce timer interrupts.
