### ISSUE TITLE
Support filling in new "statistics"

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rustc-perf#146]
I think there's logic to backfill new benchmarks, but it may be nice to also backfill new statistics, such as https://github.com/rust-lang-nursery/rustc-perf/issues/145

**Comment by Mark-Simulacrum** [comment]
We can change the data storage format to look more like the following, and then modify the back filling code to check for missing statistics as well, instead of just benchmarks.

```
file (commit-sha.json)
{
    "benchmarks": {
        "name": {    
            "statistics": {
                "size": 199,
                "time": 1000
            },
        },
    },
    "commit": "hash",
    "date": "2017-09-01..."
}
```

**Comment by rylev** [comment]
I think this is not longer relevant as the site should be able to handle new statistics now that it uses a database.
