### ISSUE TITLE
Error message appears when opening compare page: Failed to deserialize request: Error("unknown variant `instructions:u

### ISSUE THREAD

**Issue by klensy** [rust-lang/rustc-perf#1493]
Open for example https://perf.rust-lang.org/compare.html?start=5b3e9090757da9a95b22f589fe39b6a4b5455b96&end=452cf4f7109f58433ac38be7d3da527408571054&stat=instructions:u%27

And see error message box:

```Failed to deserialize request: Error("unknown variant `instructions:u'`, expected one of `context-switches`, `cpu-clock`, `cpu-clock:u`, `cycles`, `cycles:u`, `faults`, `faults:u`, `instructions:u`, `max-rss`, `task-clock`, `task-clock:u`, `wall-time`, `branch-misses`, `cache-misses`, `size:codegen_unit_size_estimate`, `size:dep_graph`, `size:linked_artifact`, `size:object_file`, `size:query_cache`, `size:work_product_index`, `size:crate_metadata`, `size:dwo_file`, `size:assembly_file`, `size:llvm_bitcode`, `size:llvm_ir`, `size:doc_bytes`, `size:doc_files_count`", line: 1, column: 125)```

previous PRs work ok, for example https://perf.rust-lang.org/compare.html?start=aebf7c4a0e68f0211b22ed3c7cec94779e2d83d6&end=5b3e9090757da9a95b22f589fe39b6a4b5455b96&stat=instructions:u

**Comment by Kobzol** [comment]
How did you generate this URL? It has an extra apostrophe (`'`, or `%27` when URL encoded) at the end, so the name of the metric is wrong.

**Comment by klensy** [comment]
> How did you generate this URL? It has an extra apostrophe (`'`, or `%27` when URL encoded) at the end, so the name of the metric is wrong.

Yes, by bad :-(
