### ISSUE TITLE
Support version numbers on the compare page

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rustc-perf#1517]
Right now, https://perf.rust-lang.org/compare.html?stat=instructions%3Au&start=1.66.0&end=1.67.0 gives an error that `1.66.0` isn't a commit hash. To compare the two versions, you have to manually go to https://github.com/rust-lang/rust/releases/tag/1.66.0 and see what commit hash is there. It would be nice if perf.rlo did that automatically.

**Comment by Kobzol** [comment]
Actually, this should just work: https://perf.rust-lang.org/compare.html?stat=instructions%3Au&start=1.65.0&end=1.66.0, but `1.67.0` is not in the database yet. The benchmarking of released versions used to be manual, but it should be automated now. The fact that `1.67.0` is missing is a sign of some bug.

@Mark-Simulacrum https://static.rust-lang.org/manifests.txt it looks like this list has stopped updating, therefore automatic release benchmarking doesn't work.

**Comment by Mark-Simulacrum** [comment]
I think comparing by commit hash also may not work? I'm not sure if we benchmark stable/beta merges.

(The tag-based benchmarks are also a little different, they run on a subset of the benchmarks).

**Comment by Kobzol** [comment]
@jyn514 Your original link now works.

**Comment by jyn514** [comment]
Thank you!
