### ISSUE TITLE
Add link from `compare` to `detailed-query`

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rustc-perf#1702]
I learned that if I can make my way to the detailed-query page (e.g. [here](https://perf.rust-lang.org/detailed-query.html?commit=945ab669165d66b3ab6088bece01844e36f6a029&base_commit=fc8a3e357a0a5e317132e5ff8858ec70970fb07a&benchmark=ctfe-stress-5-opt&scenario=full)), it will let me know how to run cachegrind so that I can get a diff of which functions are the main cause for the slowdown. Unfortunately when a perf run finishes I am looking at a [page like this](https://perf.rust-lang.org/compare.html?start=3071e0aef6dfd0a150c3fb1da0abad4ec86ca0aa&end=94b77248c5aa991f2597b4a1c1a49e297ac2f3e2&stat=instructions:u) and I have no idea how I can get from there to the page where the cachegrind commands are shown...

**Comment by RalfJung** [comment]
*Oh* I have to click on the percentage diff. Well that is non-obvious.^^ That number doesn't even look clickable (not blue, not underlined) so I literally only found it by clicking on every piece of text that I saw...
Maybe when I unfold the individual benchmark by clicking on the arrow (where it shows the "Benchmark info" etc), there could be an explicit link (clearly indicated as a link) to that page or so?

**Comment by Kobzol** [comment]
You have to click on the value in the `% Change` column :grin:

![image](https://github.com/rust-lang/rustc-perf/assets/4539057/3217cdb0-92fa-4322-95ad-b2d17a2cd383)

https://github.com/rust-lang/rustc-perf/pull/1694 should hopefully make this clearer.

**Comment by RalfJung** [comment]
This is fixed by https://github.com/rust-lang/rustc-perf/pull/1694 :)
