### ISSUE TITLE
compare page tab availability should not depend on currrently selected metric

### ISSUE THREAD

**Issue by klensy** [rust-lang/rustc-perf#1727]
For example, https://perf.rust-lang.org/compare.html?start=6710e3312d54f03f6462481199b9e72367a2568b&end=5899a80ae60ec0959dcd4a7eca6eb02ce2866632&stat=instructions%3Au&tab=compile

1. Select compile-time tab and instructions metric: all tabs available.
2. Select in current tab (compile-time) max-rss metric: page refreshes and runtime tab disappears.

This behavior slightly confusing. Tabs should be always available, if some metric not available, it should reset to some default one.

**Comment by Kobzol** [comment]
Right, hiding the tab was a temporary measure until we gather some runtime data. Now it should be shown, but without any entries, if there is no data for that metric. Thanks! I'll try to fix it soon.
