### ISSUE TITLE
Graph colors should be consistent

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rustc-perf#174]
We have a standard set of benchmarks (clean, clean-incremental, baseline incremental, println). The graph lines for those should be colored consistently across all graphs on the page. Otherwise it's easy to get confused.

**Comment by pnkfelix** [comment]
I remember this problem being much worse than it seems to be now, though I'm not sure what has changed to make the selection of symbols+colors somewhat more consistent across the various graphs.

However, the problem *does* still persist, to some extent. Here is an image illustrating the problem @michaelwoerister is describing:

![Screen Shot 2019-09-10 at 12 56 10](https://user-images.githubusercontent.com/173127/64608205-6d2c8700-d3ca-11e9-987d-15460f4bce12.png)

Most of the symbols+colors between the two graphs above are assigned consistently. But `incremental: patched println` is an orange upward triangle on top, while it is a purple downward triangle on the bottom.

----

One detail that slightly complicates this is that the set of benchmarks *does* vary slightly; in particular, there is a large variety of `patched incremental: foo` for various `foo` when you look at things like the issue-46449 benchmark. This probably just is an indication that we may need to take care in deciding whether solutions like "hardcode an explicit table mapping from each variant to its symbol in shared.js" are reasonable or not.

**Comment by Mark-Simulacrum** [comment]
I believe this should be largely fixed as of ae64c3b9f7c028dcea2fa4a358177070c46c0a9b, which reworked the graph backend. Specifically we always sort now, and put println first, so at least amongst those that have the "known good" set of patches (clean/baseline incr/clean incr/patched incr: println) the colors will be consistent I believe; beyond that set they may not line up perfectly but we have few that go beyond that set and those patches don't really line up that well anyway.
