### ISSUE TITLE
Stable-only benchmarks don't run locally

### ISSUE THREAD

**Issue by Nadrieril** [rust-lang/rustc-perf#1777]
Some benchmarks like `encoding` are `category: stable` instead of `category: primary/secondary`. When I run `collector bench_local --include encoding,...`, `encoding` is not run. Is there a way to make it run, short of locally changing its `category`?

**Comment by Kobzol** [comment]
It's not currently possible because of [this](https://github.com/rust-lang/rustc-perf/blob/d4d352fe6e8f330129387ecfb18fde7dae18a96d/collector/src/bin/collector.rs#L908). We can probably just remove that line though.

Out of curiousity, what is your use-case for running a stable benchmark?

**Comment by Nadrieril** [comment]
Removing this line would fix my problem :D Maybe `--include primary,secondary` could filter just these for anyone who needs that? I only ever run a selected set of benchmarks myself since I only touch match checking.

My use-case is testing whether we can remove an old hack that specifically regressed `encoding` ([here](https://github.com/rust-lang/rust/pull/119112)).

**Comment by Kobzol** [comment]
@nnethercote Did you have any specific motivation for disabling stable benchmarks in `bench_local`?

**Comment by nnethercote** [comment]
Because running the stable benchmarks locally is almost never what you want to do. More detail [here](https://github.com/rust-lang/rustc-perf/pull/1778#issuecomment-1865196391).
