### ISSUE TITLE
Expected end time calculation uses wrong time?

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rustc-perf#1801]
Saw this today, where the next run is expected to end +4 minutes from the currently ongoing run. My guess is that we're using the remaining time in the current run rather than the expected runtime of a run as the delta to add? Or perhaps ignoring that the current run is still ongoing?

<img width="1390" alt="image" src="https://github.com/rust-lang/rustc-perf/assets/5047365/01f2ab2b-625c-46df-a4ec-d1db740b751b">

**Comment by Kobzol** [comment]
Good catch! This was actually the combination of two separate bugs. https://github.com/rust-lang/rustc-perf/pull/1802 should help.
