### ISSUE TITLE
Fix layout of status page

### ISSUE THREAD

**Issue by Kobzol** [rust-lang/rustc-perf#1815]
The [status page](https://perf.rust-lang.org/status.html) shows a table with a timeline of benchmark runs. The table shows errors that have occurred during the run. Currently, if there is an error, and you open it, it will modify the layout of the table, and it will "jump" below the "Current collection" column, because of the usage of `flex-wrap: wrap`.

It would be great to tweak the CSS slightly, so that it doesn't jump around the page.

**Comment by Maniktherana** [comment]
I'd like to take this up. There aren't any errors atm tho where I can reporduce this

**Comment by Kobzol** [comment]
You would have to simualte errors locally, e.g. by building a benchmark from the suite and adding an artificial compiler error into it. However, I think that this wouldn't actually work, because the status page doesn't work locally (with the SQLite database) - which is another thing that would be great to fix :sweat_smile: So the easiest option is probably to simply hardcode the error on the JavaScript side.

**Comment by s7tya** [comment]
Is the error causing behavior similar to what's shown in this GIF?

![](https://gyazo.com/eaea1f6de46fa05d3d8182fb7d2bee26.gif)

I believe the easiest solution would be to implement the following CSS:

```scss
.timeline {
  pre.error {
    max-width: 640px;
    white-space: pre-wrap;
  }
}
```

This should resolve the issue, as demonstrated in this GIF:
![](https://gyazo.com/8de896c1253d81ad25e25095c09e65e9.gif)

**Comment by Maniktherana** [comment]
@s7tya were you able to get the status page running locally as well or is this hardcoded?

**Comment by s7tya** [comment]
I'm just working with a simple hardboard 😢. I downloaded the JSON from https://perf.rust-lang.org/perf/status_page.

**Comment by s7tya** [comment]
It seems that fixing the layout and running the API server locally are two separate tasks. Wouldn't it be better to split this into two issues?

**Comment by Maniktherana** [comment]
Yes, indeed it would. But ig it would be best to have the page run locally first. I'm still figuring it out myself 🤷‍♂️

**Comment by Kobzol** [comment]
> Is the error causing behavior similar to what's shown in this GIF?
> 
> ![](https://gyazo.com/eaea1f6de46fa05d3d8182fb7d2bee26.gif)
> 
> I believe the easiest solution would be to implement the following CSS:
> (though this is just a example, so we could improve the details after)
> 
> ```scss
> .timeline {
>   pre.error {
>     max-width: 640px;
>     white-space: pre-wrap;
>   }
> }
> ```
> 
> This should resolve the issue, as demonstrated in this GIF:
> ![](https://gyazo.com/8de896c1253d81ad25e25095c09e65e9.gif)

Yes, this is exactly the UI issue I meant :)

**Comment by s7tya** [comment]
@Maniktherana 
Hi. Sorry for the ping.

If there's no updates, I'd like to do this. Because of my previous PR on this repository, now we're able to run the status page locally.

So there's just a UI thing left as I mentioned earlier in this issue. However if you're still working on this, I'd like to leave it to you, Thanks.

**Comment by Maniktherana** [comment]
@s7tya I'm not working on it, please go ahead :)

**Comment by s7tya** [comment]
@Maniktherana Thank you! I'd appreciate it. Will be creating PR shortly.
