### ISSUE TITLE
Add runtime benchmark historical chart to the dashboard

### ISSUE THREAD

**Issue by Kobzol** [rust-lang/rustc-perf#1816]
The dashboard currently contains data for `check`/`debug`/`opt`/`doc` builds. It would be nice to also add a historical chart for our runtime benchmarks to it (probably with the wall-time metric, same as for the compile benchmarks).

**Comment by s7tya** [comment]
As mentioned in #1921, the graph width is a bit large, and there would be many graphs if we add runtime ones. It might be a good idea to arrange the charts in two columns when adding runtime charts.

**Comment by Kobzol** [comment]
Could be, or we can add some mini-index, or make the individual charts collapsable. Whatever works :)
