### ISSUE TITLE
"Perf builds for each rolled up PR" table gets confused by pipe `|` characters in description

### ISSUE THREAD

**Issue by Zalathar** [rust-lang/rustc-perf#1837]
See https://github.com/rust-lang/rust/pull/121859#issuecomment-1973958656 for an example.

The bot tried to render the rolled-up perf builds in a table, but the line for https://github.com/rust-lang/rust/pull/121784 abruptly cuts off mid-description, because the issue description contains pipe characters (`||`).

Presumably they aren't being escaped by the bot, so the GitHub table renderer treats them as cell boundaries instead of visible pipe characters.

**Comment by Zalathar** [comment]
I imagine some backslash-escaping for pipe characters is needed here:

https://github.com/rust-lang/rustc-perf/blob/9580e15048a6718bda3a07c32b060d7075b89855/site/src/github.rs#L65-L83

**Comment by Kobzol** [comment]
Ah, good point, we should probably escape Markdown there.

**Comment by Kobzol** [comment]
Do you want to try to fix this? :)
