### ISSUE TITLE
"Benchmarks for artifact sizes" confuses me

### ISSUE THREAD

**Issue by chengr4** [rust-lang/rustc-perf#1869]
According to @Kobzol 's [blog](https://kobzol.github.io/rust/rustc/2023/08/18/rustc-benchmark-suite.html), The main function of `helloworld-tiny` and `ripgrep-13.0.0-tiny` are to monitor the size of  Rust executable

> Refer to blog: There are also two secondary benchmarks (`helloworld-tiny` and `ripgrep-13.0.0-tiny`), which exist solely to monitor the size of a “minimal-sized” Rust executable, which is compiled with compiler flags that should favour small executable size.

However, on the [graphs](https://perf.rust-lang.org/index.html) page, the title states 'Benchmarks for artifact sizes', but the metric displayed is "CPU instructions", which confuses me.

<img width="1105" alt="Screenshot 2024-03-20 at 11 43 43 AM" src="https://github.com/rust-lang/rustc-perf/assets/54136390/e856ab62-bda5-4581-bcf9-e75b73c6839c">

I believe it should present the value of `size:xxxxxx`.

## Solutions I come up with

1. (Simple) Write a note below the title explaining that it only makes sense when the `kind` is `size:xxxxxx`.
2.  We should separate the APIs and let them have their own behavior

---

related to : #1817

**Comment by Kobzol** [comment]
Hi, the whole graphs page is displayed with a single metric, so if you choose instructions, you'll see instruction counts for all the benchmarks.

While the binary size of these tiny benchmarks is indeed the main motivation for why we have added them, their compilation time ia actually not uninteresting! They use different compiler flags, and LTO, so it is also interesting to look at how does their compilation time change.

**Comment by Kobzol** [comment]
Feel free to think of a better label. For example, `Benchmarks optimized for binary size` or something like that.
