### ISSUE TITLE
The Intention behind the unused function `hasSpecificSelection`

### ISSUE THREAD

**Issue by chengr4** [rust-lang/rustc-perf#1879]
Hi,

In `graphs` page, I have found out the function `hasSpecificSelection` is never used. 

Just curious. Do we keep it for future feature need?

```ts
/*
 * Returns true if a specific subset of charts is selected by benchmark
 * name, profile or scenario. In that case, the regular aligned grid of charts
 * will not be shown.
 */
function hasSpecificSelection(selector: GraphsSelector): boolean {
  return (
    selector.benchmark !== null ||
    selector.profile !== null ||
    selector.scenario !== null
  );
}
```

---

path: `site/frontend/src/pages/graphs/page.vue`

**Comment by Kobzol** [comment]
Hi, this function is used on lines 75 and 148 of the same file.

**Comment by chengr4** [comment]
But we are not able to give `benchmark`, `profile` and `scenario`  any value on the `graph` page, which means `hasSpecificSelection ` is always `false`.

**Comment by Kobzol** [comment]
It cannot be selected through the UI, but it can be passed via URL parameters. It is used to link to the graphs page from the compare page. Try to click on the "History graph" button in a benchmark detail.
![image](https://github.com/rust-lang/rustc-perf/assets/4539057/e039780c-4f55-42a8-ab34-35ff05b628f9)

**Comment by chengr4** [comment]
Got it! thanks for explanation.
