### ISSUE TITLE
Parts of the codebase don't not have a license

### ISSUE THREAD

**Issue by RaphaelMarinier** [rust-lang/rustc-perf#1880]
Parts of the codebase don't not have a license, for instance:
- https://github.com/rust-lang/rustc-perf/blob/master/database
- https://github.com/rust-lang/rustc-perf/tree/master/intern
are not covered by any explicit license.

This makes re-using this project harder, as the code with no license is not open-source (e.g. cannot be legally modified, redistributed, etc..).

An MIT LICENSE file at the root of the project would make everything clearer.

(I know that the bulk of the code which is under site/ and collector/ is already explicitly covered by the MIT license, which is good).

**Comment by Kobzol** [comment]
This is more of an oversight than anything else, we consider the whole repo (apart from code under `collector/compile-benchmarks`) to be MIT-licensed. Let's try to fix it in https://github.com/rust-lang/rustc-perf/pull/1881.

**Comment by Kobzol** [comment]
There is now a top-level MIT license: https://github.com/rust-lang/rustc-perf/pull/1881.
