### ISSUE TITLE
collector should print more descriptive error if found no matches for include/exclude option

### ISSUE THREAD

**Issue by klensy** [rust-lang/rustc-perf#1886]
Error really not helpful, it should say about typo or not found benchmark, the same for exclude.

```
$ ./target/debug/collector.exe binary_stats +nightly-x86_64-pc-windows-msvc \
    --rustc2 +nightly-x86_64-pc-windows-msvc --include "helloworldasd" --profile Debug --backend Llvm
collector error: Warning: one or more unused --include entries: ["helloworldasd"]
```
See that `include` - `helloworldasd` which is unknown benchmark.

**Comment by Kobzol** [comment]
Unused in this case means that no benchmark with such name (or name part) was not found. Feel free to send a PR with better wording! :)
