### ISSUE TITLE
Instruction measurement not active for 100% of the time

### ISSUE THREAD

**Issue by eggyal** [rust-lang/rustc-perf#1892]
It looks like this was raised before in #1480, but that was closed with only a workaround.

I am witnessing the same problem, but in my case on Apple silicon (M1 Ultra, running Fedora 40 Asahi Remix):

```text
$ collector bench_local $RUSTC
Using database `results.db`
Benchmarking Id for triple aarch64-unknown-linux-gnu
44 normal benchmarks remaining
Preparing await-call-tree
Running await-call-tree: Check + [Full, IncrFull, IncrUnchanged, IncrPatched] + Llvm
thread 'main' panicked at collector/src/compile/execute/mod.rs:557:13:
measurement of `apple_icestorm_pmu/instructions:u/` only active for 18.00% of the time
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The workaround suggested in the previous issue is to use `taskset` to set CPU affinity.  In my case, this works when the affinity is set to only the 4 efficiency cores (leaving the 16 performance cores on the table):

```text
$ taskset 0x603 collector bench_local $RUSTC
Using database `results.db`
Benchmarking Modified for triple aarch64-unknown-linux-gnu
44 normal benchmarks remaining
Preparing await-call-tree
Running await-call-tree: Check + [Full, IncrFull, IncrUnchanged, IncrPatched] + Llvm
Running await-call-tree: Debug + [Full, IncrFull, IncrUnchanged, IncrPatched] + Llvm
Running await-call-tree: Opt + [Full, IncrFull, IncrUnchanged, IncrPatched] + Llvm
43 normal benchmarks remaining
# ... etc ... #
```

For the avoidance of doubt, setting the affinity to only the performance cores (mask `0xFF9Fc`) panics on the same assertion as above.

Would really be great to find a better solution than this workaround!

**Comment by Kobzol** [comment]
Hi, thanks for the report (you might be the first one who is trying `rustc-perf` on Mac hardware, lol). I don't currently have any HW that has this issue at hand at the moment, but if you can find a robust way how to get around this, I'll be happy to review a PR.

**Comment by eggyal** [comment]
I think I can see what's happening here; `perf` output includes entries for both `apple_firestorm_pmu` (the performance cores) and `apple_icestorm_pmu` (the efficiency cores).  For example:

```text
77578798318;;apple_firestorm_pmu/instructions:u/;8573687943;97.00;3.08;insn per cycle
746941881;;apple_icestorm_pmu/instructions:u/;200835583;75.00;0.03;insn per cycle
25187739015;;apple_firestorm_pmu/cycles:u/;8573687943;97.00;;
371940390;;apple_icestorm_pmu/cycles:u/;200835583;75.00;;
8774.52;msec;task-clock;8774523526;100.00;1.569;CPUs utilized
8772.70;msec;cpu-clock;8774523526;100.00;1.569;CPUs utilized
107788;;faults;8774523526;100.00;12.284;K/sec
8031;;context-switches;8774523526;100.00;915.263;/sec
<not supported>;;apple_firestorm_pmu/branch-misses/;0;100.00;;
<not supported>;;apple_icestorm_pmu/branch-misses/;0;100.00;;
<not supported>;;apple_firestorm_pmu/cache-misses/;0;100.00;;
<not supported>;;apple_icestorm_pmu/cache-misses/;0;100.00;;
```

It appears (on my system, at least) that `perf stat` has a `--hybrid-merge` option that appears to be exactly what we want; per the manual:

> Merge core event counts from all core PMUs. In hybrid or big.LITTLE systems by default each core PMU will report its count separately. This option forces core PMU counts to be combined to give a behavior closer to having a single CPU type in the system.

Unfortunately, even if that is indeed correctly aggregating the counters, it doesn't appear to be aggregating the percentages:

```
3958113648800;;instructions:u;509913437611;80.00;2.32;insn per cycle
1706792652003;;cycles:u;509913437611;80.00;;
509913.44;msec;task-clock;509913437611;100.00;15.797;CPUs utilized
509842.23;msec;cpu-clock;509913437611;100.00;15.795;CPUs utilized
3560659;;faults;509913437611;100.00;6.983;K/sec
230248;;context-switches;509913437611;100.00;451.543;/sec
<not supported>;;branch-misses;0;100.00;;
<not supported>;;cache-misses;0;100.00;;
```

Therefore I propose parsing the original output, and performing the merge ourselves.  Would that be acceptable?

**Comment by Kobzol** [comment]
I'm not sure if we can really interpret the results across different core counts by just summing them. But as long as it produces the same output on Linux and "classic" cores, I think that aggregating all the values for the same metric together should be fine.

**Comment by eggyal** [comment]
I've [asked](https://lore.kernel.org/linux-perf-users/CA+phaecbKJXE56ExeJUA5c2=tc3m3p8iNefuqyjs9P3kOn_aWg@mail.gmail.com/T/#u) about these percentages on the linux-perf-users list.

**Comment by eggyal** [comment]
Actually, the [multiplexing and scaling events](https://perf.wiki.kernel.org/index.php/Tutorial#multiplexing_and_scaling_events) section of the wiki explains it quite well.

**Comment by Mark-Simulacrum** [comment]
The goal of the percentage checking (at least as I recall adding it...) is precisely that we don't want multiplexing, instead we want to bail out entirely if the kernel didn't manage to allocate enough counters for all of the metrics we asked it to. It seems plausible that on the Apple hardware the kernel either doesn't know how to or isn't able to configure enough counters for all of the metrics we're asking it to? I don't know off hand how many performance counters the Apple chips have...

My sense is that we should not try to workaround multiplexing by doing anything in our code (e.g., summing) but instead should try to find/suggest a configuration that is able to use counters without multiplexing them. I'm not sure if there's a way to tell `perf` to bail if it can't run a configuration without multiplexing...

**Comment by eggyal** [comment]
I'll just do what [this comment](https://www.reddit.com/r/AsahiLinux/s/8O0JABbK8r) on the AsahiLinux subreddit recommends and select only the firestorm events together with setting affinity to only those cores.

The event selection is (currently) hardcoded in `rustc-fake`, but I'm happy just to modify in my local fork and leave it at that.

Thanks all!  Every day's a school day.  :)
