### ISSUE TITLE
A way to use regex to filter benchmarks would be nice

### ISSUE THREAD

**Issue by Zentrik** [rust-lang/rustc-perf#1900]
Presumably we could have a toggle by the search bar to switch to regex mode.

**Comment by Kobzol** [comment]
Given that the current string filter is essentially a subset of a regex, I don't think that we even need a toggle, we can just switch to a regex and it should stay backwards compatible, while also offering new functions.

For context, the benchmark search bar is on the [compare page](https://perf.rust-lang.org/compare.html):
![image](https://github.com/rust-lang/rustc-perf/assets/4539057/60899d09-cb76-447d-9d50-40ef949393da)

**Comment by Zentrik** [comment]
I was concerned if the benchmark names had special characters in them but looks like the only offending character for the rust benchmarks are . and that's not really a big deal.

Anyways here's the search code
https://github.com/rust-lang/rustc-perf/blob/c1abcdbcb38b886f1d96eb8d5575fa38b7095904/site/frontend/src/pages/compare/runtime/common.ts#L28
https://github.com/rust-lang/rustc-perf/blob/c1abcdbcb38b886f1d96eb8d5575fa38b7095904/site/frontend/src/pages/compare/compile/common.ts#L163
