### ISSUE TITLE
Dashboard should use log-scale and have a smaller aspect ratio

### ISSUE THREAD

**Issue by the8472** [rust-lang/rustc-perf#1901]
Currently on my desktop the dashboard charts look like this

![image](https://github.com/rust-lang/rustc-perf/assets/1065730/08fbf9e3-802a-41f0-b2ef-5642776d95f2)

Due to the exponential downwards trend each incremental change becomes more more difficult to distinguish. Changing the aspect ratio to make the Y-axis taller would help to some extent. But I think we should use a log-scale, for the same reasons as @scottmcm already argued in https://github.com/rust-lang/rustc-perf/issues/192#issuecomment-394611567

If it's easy to toggle the charting library between linear and log then adding some toggle for that would be fine too. Then people who know how to read log scales can choose that.

**Comment by Kobzol** [comment]
It's not much better if we just switch to a log-scale:
![image](https://github.com/rust-lang/rustc-perf/assets/4539057/b787e11d-a4b8-47a8-ac94-df291a1527e2)

Maybe it would be better to normalize it vs the `1.28.0` baseline instead, as discussed [here](https://rust-lang.zulipchat.com/#narrow/stream/247081-t-compiler.2Fperformance/topic/log.20scale.20for.20the.20dashboard).

**Comment by the8472** [comment]
Well that seems to make the effective aspect ratio worse due to the y-axis offset wasting a lot of vertical space.

**Comment by nnethercote** [comment]
When looking at those graphs I always massively shrink the width of my browser window, which makes it more readable. Perhaps we could just restrict the graph width to achieve the same effect automatically?

**Comment by s7tya** [comment]
Due to #1816, the graphs now always have a smaller width. Therefore, it might be okay to close this issue.

**Comment by Kobzol** [comment]
Now with two charts per row it's indeed much better. I wonder how would it look like with the log scale now, could you please try it?

**Comment by s7tya** [comment]
Alright! Will try

**Comment by s7tya** [comment]
@Kobzol I took too much time to work on this. Here's the log scale version of the dashboard. How do you think?

![Image](https://github.com/user-attachments/assets/352e579b-4b57-4057-a326-75d7963bd409)
![Image](https://github.com/user-attachments/assets/2eac3542-2d3a-4446-9f07-65253e3f1f65)

**Comment by s7tya** [comment]
the screenshot of current linear scale for convenience:

![Image](https://github.com/user-attachments/assets/e1a5ac00-6263-4b90-810f-ce010878fff2)

**Comment by the8472** [comment]
They're wasting a lot of space which vertically compresses the chart which eats up any gains we might get from it being a log chart.

![Image](https://github.com/user-attachments/assets/9cd485a5-06e3-460d-9ff1-cf617d5162c6)

**Comment by s7tya** [comment]
Ah, I see. Then, how about this one?
I set the minimum of the chart range to the data's lowest value and use a log scale.

![Image](https://github.com/user-attachments/assets/4473ffa9-b5a3-437e-a29e-c5bc98b19b3d)

**Comment by Kobzol** [comment]
Yeah, that looks much better, good idea! I'd still vote for a simple switch at the top of the page to allow selecting linear/log scale axes :)

**Comment by s7tya** [comment]
Which option should be the default: log scale or linear scale?
