### ISSUE TITLE
Show existing data when opening the site locally

### ISSUE THREAD

**Issue by Kobzol** [rust-lang/rustc-perf#1920]
When you run the site locally, and open the `compare.html` page (which is shown by default), you will be greated with a very annoying error message (which essentially tells you that the backend has panicked, or something like that). It would be great if the default view for `compare.html` examined the database, and tried to show some reasonable data by default, e.g. the latest entry found in the DB and -30 days before that (same as what it does on the production web).

If there is only a single commit, it should be compared with itself (this can be useful to see absolute numbers of the benchmark metrics), to again avoid showing the error message.

**Comment by s7tya** [comment]
I'm fully supporting this. I always remember the magical period "from 2024-02-20 to 2024-02-25" while working on the compare page locally.

**Comment by s7tya** [comment]
Currently, it attempts to get commits from the past 30 days using `chrono::Utc::now().date_naive() - chrono::Duration::days(30)`. However, the latest commit available via `fetch-latest` is from 2024-03-14. It cannot find any commits after 2024-05-10, which is 30 days ago from today.

https://github.com/rust-lang/rustc-perf/blob/8d37b0859c02f29afaf7ed34bb89650193d8026e/collector/src/lib.rs#L49-L52

I am wondering how to solve this problem. The first idea that came to mind is to add conditions to include commits within 30 days from the latest commit here:

https://github.com/rust-lang/rustc-perf/blob/8d37b0859c02f29afaf7ed34bb89650193d8026e/site/src/selector.rs#L48
