### ISSUE TITLE
License the whole `rustc-perf` repository under the MIT license

### ISSUE THREAD

**Issue by Kobzol** [rust-lang/rustc-perf#1933]
This repository currently does not have a top-level LICENSE file (#1880), which means that not all of its code is covered by a license.
We would like to license the whole `rustc-perf` repository (apart from the `collector/compile-benchmarks` directory, which has its own licenses) under the MIT License, to make it [easier](https://github.com/rust-lang/rustc-perf/issues/1880) to use `rustc-perf` in `rustc` source distributions. In the future, we might want to extend this license to MIT/Apache 2.0 (although currently we're aiming at MIT, as a start, since it is easier), hence we would like to ask the contributors to agree with a dual MIT/Apache 2.0 license, as a sort of future-proofing.

To do that, **we need contributors that made commits to this repository** (with some caveats, see below) **to agree by posting a comment stating their approval to this issue**. Please see instructions at the bottom of this issue if you are mentioned in the list below. I will try to also contact the contributors individually.

<details>
<summary>How did we select the list of contributors from whom we need the approval?</summary>

I analyzed the commits from `rustc-perf` going all the way back to [`e99853d4777a1df001853c619eead0c891c28488`](https://github.com/rust-lang/rustc-perf/commit/e99853d4777a1df001853c619eead0c891c28488). In this commit, there was a top-level MIT license at the root of the repository, therefore all earlier commits should be MIT licensed. Then I found a set of contributors that made at least a single commit to any other directory than `collector` and `site`, because these two were already MIT licensed.

I used [this](https://gist.github.com/Kobzol/f6abec15c398759d06feaa1aed86f71f) script for performing the analysis.

</details>

Related issues: https://github.com/rust-lang/rustc-perf/issues/1880, https://github.com/rust-lang/rustc-perf/issues/1927
PR with the new license: https://github.com/rust-lang/rustc-perf/pull/1881

# Checkoff
To agree to the licensing terms, please comment with the following text on this issue (you can copy the text using the copy button on the right):
```
I license past and future contributions to the `rust-lang/rustc-perf` repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.
```
Thank you very much!

Affected contributors:

- [x] @Mark-Simulacrum
- [x] @Kobzol
- [x] @rylev
- [x] @nnethercote
- [x] @pnkfelix
- [x] @klensy
- [x] @tgnottingham
- [x] @ecstatic-morse
- [x] @jyn514
- [x] @wesleywiser
- [x] @s7tya
- [ ] @Horki
- [x] @weihanglo
- [x] @homersimpsons
- [x] @eth3lbert
- [x] @pietroalbini
- [x] @chengr4
- [x] @blyxyas
- [x] @miwig
- [x] @kennytm
- [x] @jsha
- [x] @GuillaumeGomez
- [x] @sn99
- [x] @apiraino
- [x] @est31
- [x] @eddyb
- [x] @RalfJung
- [x] @alex
- [x] @ishitatsuyuki
- [x] @alexcrichton
- [x] @SimonSapin

**Comment by Kobzol** [comment]
I license past and future contributions to the `rust-lang/rustc-perf` repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by GuillaumeGomez** [comment]
I license past and future contributions to the `rust-lang/rustc-perf` repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by ishitatsuyuki** [comment]
I license past and future contributions to the `rust-lang/rustc-perf` repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by homersimpsons** [comment]
I license past and future contributions to the `rust-lang/rustc-perf` repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by s7tya** [comment]
I license past and future contributions to the `rust-lang/rustc-perf` repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by blyxyas** [comment]
I license past and future contributions to the `rust-lang/rustc-perf` repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by sn99** [comment]
I license past and future contributions to the `rust-lang/rustc-perf` repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by kennytm** [comment]
I license past and future contributions to the `rust-lang/rustc-perf` repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by weihanglo** [comment]
I license past and future contributions to the `rust-lang/rustc-perf` repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by rylev** [comment]
I license past and future contributions to the `rust-lang/rustc-perf` repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by alexcrichton** [comment]
I license past and future contributions to the `rust-lang/rustc-perf` repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by alex** [comment]
I license past and future contributions to the `rust-lang/rustc-perf` repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by eth3lbert** [comment]
I license past and future contributions to the rust-lang/rustc-perf repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by pnkfelix** [comment]
I license past and future contributions to the rust-lang/rustc-perf repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by SimonSapin** [comment]
I license past and future contributions to the `rust-lang/rustc-perf` repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by wesleywiser** [comment]
I license past and future contributions to the `rust-lang/rustc-perf` repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by klensy** [comment]
I license past and future contributions to the `rust-lang/rustc-perf` repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by jsha** [comment]
I license past and future contributions to the `rust-lang/rustc-perf` repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by nnethercote** [comment]
I license past and future contributions to the rust-lang/rustc-perf repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by chengr4** [comment]
I license past and future contributions to the `rust-lang/rustc-perf` repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by jyn514** [comment]
... good luck.

---

I license all my past contributions to the rust-lang/rustc-perf repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by est31** [comment]
I license all my past contributions to the rust-lang/rustc-perf repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by Mark-Simulacrum** [comment]
I license past and future contributions to the `rust-lang/rustc-perf` repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by apiraino** [comment]
I think I don't need to make any licensing explicit on my end since my only contribution was a [typo fix](https://github.com/rust-lang/rustc-perf/pull/1160) in a perf. triage report :smile: but anyways

I license past and future contributions to the rust-lang/rustc-perf repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by pietroalbini** [comment]
I license past and future contributions to the `rust-lang/rustc-perf` repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by miwig** [comment]
I license past and future contributions to the `rust-lang/rustc-perf` repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by tgnottingham** [comment]
I license past and future contributions to the `rust-lang/rustc-perf` repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by eddyb** [comment]
I license past and future contributions to the `rust-lang/rustc-perf` repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by ecstatic-morse** [comment]
I license past and future contributions to the `rust-lang/rustc-perf` repository under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by Kobzol** [comment]
So, we got `30/31` approvals in 5 (!) days, that is awesome! Big thanks to everyone who expressed their approval.

The last remaining contributor who didn't express their approval yet, @Horki, [contributed code](https://github.com/rust-lang/rustc-perf/commits/master/?author=Horki) that was since deleted and is no longer a part of this repository. Therefore I think that we should be good with moving forward with the licensing.

**Comment by Kobzol** [comment]
A top-level MIT license has been added: https://github.com/rust-lang/rustc-perf/pull/1881.
