### ISSUE TITLE
Improve rendering of history graphs

### ISSUE THREAD

**Issue by Kobzol** [rust-lang/rustc-perf#1938]
When you open the [graph history](https://perf.rust-lang.org/index.html) page with a single graph selected (common when coming from the compage page), it would be nice to show the graph over the full page, rather than just in a small box.

Also, some improvements could be made to improve the readability of the graph when it contains a wide range of values (https://github.com/rust-lang/rustc-perf/pull/1936#issuecomment-2208390792).

**Comment by s7tya** [comment]
is this mean expanding the width of graph to the screen width?
![CleanShot 2024-07-11 at 16 28 31@2x](https://github.com/rust-lang/rustc-perf/assets/53410646/285b4d87-cb6d-4379-8249-a77a23040b6f)

**Comment by s7tya** [comment]
I see. it might be nice to check if both benchmark & profile option are set to determine single graph is selected.
