### ISSUE TITLE
Odd gray region to right of graph after zooming in

### ISSUE THREAD

**Issue by Zentrik** [rust-lang/rustc-perf#1983]
To reproduce go to https://perf.rust-lang.org/compare.html and zoom in on any graph. (I've tested on Firefox and Edge on Linux)
![Image](https://github.com/user-attachments/assets/c2788dc7-7279-466d-b977-ee9975e6e896)

I couldn't figure out where in the code this was appearing from.

**Comment by Kobzol** [comment]
Hmm, this should be intended :) It shows the data that arrived after that commit, it is described in the graph description.

**Comment by Zentrik** [comment]
I don't think that's the case here. Does https://perf.rust-lang.org/compare.html not default to the newest commit? Also usually then there would be data in the grey region.
If this was because of new data, surely zoomed out the region would also be present. But it's not,![Image](https://github.com/user-attachments/assets/38d0101c-922e-48ce-b690-55d19ff90f4a)

Further the grey region seems to be outside of the graph (Notice the graph is bounded to the same region in both pictures)
![Image](https://github.com/user-attachments/assets/d3258854-4f20-4712-9cc8-a33662350e08)

It seems if the grey region is not supposed to be present, when zooming in, it ends up to the right of the graph.

**Comment by Kobzol** [comment]
Ah, I see now, yeah, that's a bug. You don't even need to zoom in. It should only be shown for date after the benchmarked commit, but it's alos shown for previous dates:
![Image](https://github.com/user-attachments/assets/001d9cf4-99f9-4bc1-bd09-69cd7dad385c)

**Comment by s7tya** [comment]
I think this is because of this code. We also have duplicated thing for runtime benchmarks.

https://github.com/rust-lang/rustc-perf/blob/de7ce9e50bec155a2d2dba9512eb6c554c193e57/site/frontend/src/pages/compare/compile/table/benchmark-detail-graph.vue#L154-L173
