### ISSUE TITLE
Mismatched headers on the runtime tab

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rustc-perf#2004]
The table headers are missing a column corresponding to the arrow icon, causing the headers and data to be shifted by 1 column relative to each other.

![Image](https://github.com/user-attachments/assets/e4598971-4793-402e-a21e-ed26773decf0)

**Comment by Kobzol** [comment]
Thanks for the report! I completely missed this. @s7tya Do you want to take a look? If not, I'll fix this.

**Comment by s7tya** [comment]
I'll do this in a week! (I'm bit busy until tomorrow)
