### ISSUE TITLE
Add some kind of fairness-mechanism to benchmark scheduling

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rustc-perf#271]
Currently there's [a case](https://github.com/rust-lang/rust/pull/53356#issuecomment-413223750) where a try-build has been executed for a while but the baseline for is way towards the end of the benchmarking queue, while at the same time new jobs get pushed to the front of the queue almost as fast as they can be processed. As a result it will take an unbounded amount of time until the try-build can be usefully checked for performance regressions. 

It would be great if older benchmarking jobs would have a higher priority than newer ones, or jobs that are needed as a baseline for try builds would have a higher priority, or there was at least some randomization of priorities so that no single job will have to wait forever.

In the long run we should probably do benchmarking on more than one machine at once.

**Comment by RalfJung** [comment]
Seems like actually having a *queue* (the job that waited the longest runs next) instead of what looks to be more like a stack would do it?

**Comment by michaelwoerister** [comment]
Yes, that would be an improvement.

**Comment by Mark-Simulacrum** [comment]
That's not quite ideal because if we've missed one commit a couple days ago it's not generally critical that we get data for it, whereas data for more recent commits is generally more desirable.

**Comment by Mark-Simulacrum** [comment]
I believe we've not had too many issues with this lately. The current algorithm, roughly, is that a try commit gets priority and hoists its parent to run before it (such that when the try commit's own build is finished, the results are fully ready). Beyond that we schedule most recent commits first.

**Comment by nnethercote** [comment]
I agree the current algorithm is working well.
