### ISSUE TITLE
Provide "site" without a fresh full git clone

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rustc-perf#292]
Following the README, I started the "site" and expected it to render a diff like [this](https://perf.rust-lang.org/compare.html?start=c67ea54d4466f1c082f72b194c100bb4954449e6&end=98f2e1baba46136fa7a09100c2a7d6d524226d67), I thought that's what it is for? I would appreciate if you could provide that functionality without consuming 500MB of disk space on another (my 4th) full clone of the Rust soure code.

Also, the README just nonchalantly says "The first time you do this the rustc repository is cloned" as if that was a natural thing to do for a server supposed to render a few numbers. I don't think it is, so I'd appreciate if you could let us know what this is for. Just so we at least know what we are sacrificing all that space for ;) .

Alternatively, it would be nice to at least have the option to point it to an existing clone, assuming it won't change that clone (i.e., it must not touch the working copy or change any of my branches around or so).

**Comment by Mark-Simulacrum** [comment]
The clone is *probably* avoidable, at least in theory, for just the comparison view. The reason we need it in general is for the interpolation and determination of what commits need to be benchmarked. It's likely we could provide the option to either point at an existing clone or just pretend it doesn't exist or something...

**Comment by RalfJung** [comment]
> The reason we need it in general is for the interpolation and determination of what commits need to be benchmarked.

Ah I see. Yeah that part of the functionality does not make much sense when used locally, does it?

**Comment by Mark-Simulacrum** [comment]
This is now merged -- none of the code will clone a rust-lang/rust instance.
