### ISSUE TITLE
commit selector style

### ISSUE THREAD

**Issue by fbstj** [rust-lang/rustc-perf#501]
the commit selector form `#commits` in `compare.html` is not very "form-like"

particularly the submit button is hard to discover, but in general that form is hard to discover too

**Comment by Mark-Simulacrum** [comment]
Generally speaking it's not intended to be super accessible -- most of the time compare pages are reached either via links from PR results or the graph (index.html) page.

Concrete suggestions (or, better, PRs) on how to improve here are welcome.

**Comment by rylev** [comment]
Closing this as the UI is definitely more form like now
