### ISSUE TITLE
Add some async/generators-using crate to the list of benchmarked stuff

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rustc-perf#506]
Maybe hyper?

**Comment by nnethercote** [comment]
We have an old version of hyper in the benchmark suite (0.5.0). I see they're up to 0.13 now. We could retire the old benchmark, and call the new one `hyper-0.13`.

**Comment by rylev** [comment]
Clossing this as we have quite a few async related benchmarks now including:
* https://github.com/rust-lang/rustc-perf/tree/master/collector/benchmarks/tokio-webpush-simple
* https://github.com/rust-lang/rustc-perf/tree/master/collector/benchmarks/hyper-2
* https://github.com/rust-lang/rustc-perf/tree/master/collector/benchmarks/deeply-nested-async
