### ISSUE TITLE
detailed comparison view: Add column for absolute delta of time values

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rustc-perf#530]
Currently the comparison page only shows the absolute value of commit B and a percentage of change of B over A. WG-self-profiling decided that we also want to have a column showing the absolute delta (in seconds), as in:

 % Total Time | Time | Δ (sec) | Δ (%) | Invocations | Δ | Loading | Δ (sec) | Δ (%) |
-- | -- | -- | -- | -- | -- | -- | -- | -- |

**Comment by Mark-Simulacrum** [comment]
We now display both absolute and percentage deltas in all diff columns.
