### ISSUE TITLE
detailed view: Add a table giving a description of what each column means exactly

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rustc-perf#532]
There's already a sentence describing `% total time`: 
> Totals row '%total time' is as a comparison to the 'cpu-clock' stat (we do not use wall-time as we want to account for parallelism).

I think this should be turned into a table with a proper description of every column.

**Comment by Mark-Simulacrum** [comment]
@wesleywiser Could you perhaps provide such a table? I guess maybe we should link to https://github.com/rust-lang/measureme/blob/master/summarize/Readme.md#reading-the-output at least? Here's a sample page: https://perf.rust-lang.org/detailed-query.html?commit=89530668eb34ae5856fd9aabf52a7c8afaa08808&base_commit=43271a39adc26d29350d4830b594c6435472815e&benchmark=script-servo-opt&run_name=incr-patched:%20println

**Comment by Mark-Simulacrum** [comment]
Hm, so actually reading that I think my understanding of what "executions" are (or "Item count" in self-profile parlance) is wrong perhaps? That is, maybe they *do* include cache hits. I guess there's two understandings of cache hits -- there's the "rustc has executed this query in the current session" and the "rustc has executed this query in a previous incremental session" sense. I'm not sure if that distinction is important here though.
