### ISSUE TITLE
Option to only run a certain kind of benchmarks

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rustc-perf#632]
For example only debug builds, but not check or opt builds.

**Comment by nnethercote** [comment]
The `bench_local collector` and `collector profile` commands can already do this, see the `--builds` and `--runs` flags [here](https://github.com/rust-lang/rustc-perf/blob/master/collector/README.md).

Or are you talking about CI runs done with `rust-timer`?

**Comment by bjorn3** [comment]
Thanks! Missed those flags.
