### ISSUE TITLE
Improve "detailed-query.html" column headers

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rustc-perf#648]
Looking at a page like https://perf.rust-lang.org/detailed-query.html?commit=89530668eb34ae5856fd9aabf52a7c8afaa08808&base_commit=43271a39adc26d29350d4830b594c6435472815e&benchmark=script-servo-opt&run_name=incr-patched:%20println, I am quite confused -- it [took me a while](https://github.com/rust-lang/rust/pull/71946#issuecomment-625326045) to figure out what these columns mean.

As a concrete suggestion, I think the three columns titled `Δ` (which looks like an upwards arrow indicating sort order, not an actual title) should get proper titles, like "Time delta", "Full executions delta" and "Loading delta" (assuming that's what they are).

Beyond that, "Full executions" and "Loading" are somewhat puzzling concepts. I would understand "executions", that's probably "how often did this thing run", but why "full"? And for "loading" I do not have the slightest clue what that might be.

**Comment by RalfJung** [comment]
Also maybe the "time" and "total time" columns should be swapped, so that the delta column is always next to the thing it is the delta of?

**Comment by Mark-Simulacrum** [comment]
Full executions is the number of times the query *actually* ran vs. the number of times it was invoked (and possibly hit the cache).

Loading time is the time it took for us to "deserialize" query results from incremental cache, I think, though possibly also metadata?

**Comment by RalfJung** [comment]
> Full executions is the number of times the query actually ran vs. the number of times it was invoked (and possibly hit the cache).

Ah. That's what I would have already expected with "executions".

> Loading time is the time it took for us to "deserialize" query results from incremental cache, I think, though possibly also metadata?

I see. Maybe "Loading cache" or "deserialize" would be better.
Or there could just be a bit of text above the table explaining this (like there already is for the "Totals row '%total time'").

**Comment by Mark-Simulacrum** [comment]
Did some work on this in 81f6f7dd981b7ef45cf35d388bc65319a178523b, which hopefully helps here. Feel free to close (or provide further feedback).

**Comment by Mark-Simulacrum** [comment]
Actually I'm going to go ahead and close -- please leave a comment/reopen/whatever if you have further feedback.
