### ISSUE TITLE
Long benchmark names are truncated even when "..." is longer than what it replaces.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rustc-perf#650]
E.g. `wf-projection-stress-65510-che...` - the elided part is `ck`, which is shorter than `...`

Also, the `...` doesn't seem to use a browser feature (IIRC there are CSS properties for automatic text elision), so that's an alternative that might be more foolproof (and maybe more accessible/user-friendly).

**Comment by nnethercote** [comment]
Better elision would be nice, but reducing the length of this benchmark's name would also be nice. `wf-proj-stress`? :)

**Comment by eddyb** [comment]
That reminds me... I don't know what happened to https://github.com/rust-lang/rustc-perf/pull/566#issuecomment-559293518.

**Comment by Mark-Simulacrum** [comment]
It's not too bad but involves stopping the collector and synchronizing a update to the data with that which is a pain -- I should just do it sometime though.

**Comment by rylev** [comment]
This is no longer an issue as we no longer truncate the benchmark name
