### ISSUE TITLE
Replace most collector logging with printing to stderr.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rustc-perf#651]
That is, instead of `trace!`, use `eprintln!`, in the `collector`.
(suggested by @Mark-Simulacrum)

<hr/>

My own motivation for this:
By the time I realize that I want more output, it's too late to add `RUST_LOG=collector=trace`.
Printing by default should be more ergonomic (assuming it's not too verbose, i.e. only used for coarse steps like downloading a toolchain, running a benchmark, etc.).

**Comment by Mark-Simulacrum** [comment]
@nnethercote -- interested in hearing if you also would prefer to log more by default.

**Comment by nnethercote** [comment]
I use wrapper scripts to run `collector` and they all have `RUST_LOG=info` in them. And the `collector` docs also tell you to use `RUST_LOG=info`.

So, defaulting to that level of output would be sensible.

(On the general topic of output, when running `collector bench_local` every run produces several lines of perf output, which I would prefer not to see. I haven't gotten around to working out how to hide that.)
