### ISSUE TITLE
We shouldn't be showing fractional parts (.000) on strictly integral values.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rustc-perf#653]
I've noticed it on "Executions" counts (specifically the deltas) in the self-profiling view, but @Mark-Simulacrum also brought up other values, like instruction counts (which have `.00`).

**Comment by rylev** [comment]
I looked around and didn't see any cases of this. I'm going to close. Feel free to reopen should you find any occurrences of this. 

<img width="99" alt="Screenshot 2021-07-29 at 16 10 53" src="https://user-images.githubusercontent.com/1327285/127507182-9fb54a3c-81b4-45f9-9e02-1cd2fa85f144.png">
