### ISSUE TITLE
Update `script-servo` benchmark

### ISSUE THREAD

**Issue by nnethercote** [rust-lang/rustc-perf#664]
The `script-servo` benchmark is about 3 years old, and recently a change took place that reduced the amount of generated LLVM IR from 10.2M lines to 7.2M lines, by avoiding bloat for one crucial function: https://github.com/servo/servo/issues/26585

With that in mind it might be a good time to retire `script-servo` and introduce `script-servo-2`. It's not one of the "stable" benchmarks so there should be no problem with this.

**Comment by Mark-Simulacrum** [comment]
Seems good! I can probably take a look at doing this soon.

**Comment by SimonSapin** [comment]
Let me know if I can help

**Comment by Mark-Simulacrum** [comment]
@SimonSapin What features should we enable for perf? `gecko`? Ideally we want a fairly stable build, so minimizing nightly dependencies would be good -- I guess gecko is that?

**Comment by SimonSapin** [comment]
The `script` crate doesn’t have a `gecko` feature. The `style` crate does, but as far as I remember it is has external dependencies that are tricky to fulfill without building all of Gecko. `script/Cargo.toml` contains `style = { path = "../style", features = ["servo"] }` which enables the `servo` feature which is mutually exclusive with `gecko`.

These days the `style` crate also has `servo-layout-2013` and `servo-layout-2020` features. Neither is enabled by default in `Cargo.toml`, but selecting one is required for the crate to compile. (When building Servo, our build system that wraps `cargo build` normally selects one of them. *It* has a default.) For the purpose of this benchmark it doesn’t really matter which one you choose, but switching to the other one in a second build could be an interesting test case for incremental compilation. (Layout 2020 has fewer CSS properties − and corresponding Rust types and enum variants − enabled at compile-time than Layout 2013 at the moment.)

Disabling default features of the `script` crate should disable the compile plugin (through the `unrooted_must_root_lint` feature), which is the most unstable part in compiler upgrades.

**Comment by SimonSapin** [comment]
> Disabling default features of the `script` crate should disable the compile plugin

I tried this and it doesn’t work without replacing `#![plugin(script_plugins)]` with `#![cfg_attr(feature = "unrooted_must_root_lint", plugin(script_plugins))]` (or just removing it).

Also `#![cfg_attr(not(feature = "unrooted_must_root_lint"), allow(unknown_lints))]` doesn’t work anymore, I get hundreds of warnings like this:

```rust
warning: unknown lint: `unrooted_must_root`
   --> components/script/script_thread.rs:483:9
    |
483 | #[allow(unrooted_must_root)]
    |         ^^^^^^^^^^^^^^^^^^
```

**Comment by SimonSapin** [comment]
Maybe the `style-servo` benchmark could also be updated at the same time. It is not affected by https://github.com/servo/servo/issues/26585 but also has received years of evolution.

**Comment by nnethercote** [comment]
`style-servo` is one of the "stable" benchmarks used for the [dashboard](https://perf.rust-lang.org/dashboard.html), which means that updating it would be more disruptive, unfortunately.

**Comment by Mark-Simulacrum** [comment]
Yeah, I want to update script-servo first, but I do think it may be viable to update style-servo and recollect the release (dashboard) builds -- that realistically doesn't take too long.

**Comment by Mark-Simulacrum** [comment]
Hm, so it looks like we need x11 headers for mozangle to build? Is there a way to turn off x11 as a dependency or x11 perhaps? It looks like there's not too much usage in the script crate.

After I installed libx11-dev on Ubuntu, I'm hitting this error: I have no idea which bytes-like object here is expected, will be investigating...

```
error: failed to run custom build command for `mozjs_sys v0.68.1 (https://github.com/servo/mozjs?rev=9a6d8fc6b0cf13cd02efbd805ccdf62ddc5ce593#9a6d8fc6)`

Caused by:
  process didn't exit successfully: `/tmp/.tmpKzKFEL/target/debug/build/mozjs_sys-0dec9d7c8918ee3b/build-script-build` (exit code: 101)
--- stdout
cargo:outdir=/tmp/.tmpKzKFEL/target/debug/build/mozjs_sys-745651a0d32f402f/out/build
[[ '/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs'/js/src/configure -ot '/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs'/js/src/configure.in ]] && touch '/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs'/js/src/configure || true
[[ '/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs'/js/src/old-configure -ot '/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs'/js/src/old-configure.in ]] && touch '/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs'/js/src/old-configure || true
! [[ '/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs'/js/src/configure.in -ot '/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs'/js/src/configure ]] && touch '/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs'/js/src/configure || true
! [[ '/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs'/js/src/old-configure.in -ot '/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs'/js/src/old-configure ]] && touch '/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs'/js/src/old-configure || true
if [[ '/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs'/js/src/configure -nt config.status ]] ; then \
  PYTHON="python2" MOZ_TOOLS="" \
  CC="gcc" CFLAGS="" \
  CPP="gcc -E" CPPFLAGS="-I/home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/encoding_c_mem-0.2.6/include " \
  CXX="g++" CXXFLAGS="" \
  AS="" AR="ar" \
  STLPORT_LIBS="" \
  '/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs'/js/src/configure --disable-jemalloc --disable-js-shell --disable-tests --disable-export-js --disable-shared-js --build-backends=RecursiveMake || (cat config.log && exit 1) ; \
fi

--- stderr
/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/../../configure.py:13: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  from collections import Iterable
Traceback (most recent call last):
  File "/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/../../configure.py", line 170, in <module>
    sys.exit(main(sys.argv))
  File "/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/js/src/../../configure.py", line 46, in main
    sandbox.run(os.path.join(os.path.dirname(__file__), 'moz.configure'))
  File "/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 446, in run
    self.include_file(path)
  File "/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 437, in include_file
    exec_(code, self)
  File "/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/python/mozbuild/mozbuild/util.py", line 51, in exec_
    exec(object, globals, locals)
  File "/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/moz.configure", line 7, in <module>
    include('build/moz.configure/init.configure')
  File "/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 769, in include_impl
    self.include_file(what)
  File "/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 437, in include_file
    exec_(code, self)
  File "/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/python/mozbuild/mozbuild/util.py", line 51, in exec_
    exec(object, globals, locals)
  File "/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/build/moz.configure/init.configure", line 24, in <module>
    def check_build_environment(help, dist):
  File "/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 752, in decorator
    depends = DependsFunction(self, func, dependencies, when=when)
  File "/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 129, in __init__
    sandbox._value_for(self)
  File "/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 543, in _value_for
    return self._value_for_depends(obj)
  File "/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/python/mozbuild/mozbuild/util.py", line 997, in method_call
    cache[args] = self.func(instance, *args)
  File "/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 552, in _value_for_depends
    value = obj.result()
  File "/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/python/mozbuild/mozbuild/util.py", line 997, in method_call
    cache[args] = self.func(instance, *args)
  File "/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 155, in result
    return self._func(*resolved_args)
  File "/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 1152, in wrapped
    return new_func(*args, **kwargs)
  File "/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/mozjs/build/moz.configure/init.configure", line 73, in check_build_environment
    if '\r' in data:
TypeError: a bytes-like object is required, not 'str'
cat: config.log: No such file or directory
make: *** [/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/makefile.cargo:194: maybe-configure] Error 1
thread 'main' panicked at 'assertion failed: result.success()', /home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/build.rs:177:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by SimonSapin** [comment]
The `script` crate mostly uses ANGLE for its shader translator parts, so in theory it should be possible to build that without the parts that need X11, but the `mozangle` crate build script might have have a configuration for that.

As to the Python error with bytes v.s. Unicode, that looks like a Python 2 v.s. Python 3 error. What’s `python --version` in that build environment?

**Comment by Mark-Simulacrum** [comment]
My `python --version` is Python 3.8.2. I guess it's expecting Python 2?

**Comment by SimonSapin** [comment]
Yes probably. Is `python2` or `python2.7` available?

**Comment by Mark-Simulacrum** [comment]
I didn't have them installed (surprisingly to me, actually) -- having now installed them, it looks like things are building, but I'm hitting this error now. I do have llvm-objdump-10 locally... it doesn't seem like I have a nice way of symlinking that to llvm-objdump. Should we be installing the llvm-tools-preview component?

```
--- stderr
DEBUG: llvm_objdump: Trying llvm-objdump
ERROR: Cannot find llvm-objdump
make: *** [/home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/makefile.cargo:194: maybe-configure] Error 1
thread 'main' panicked at 'assertion failed: result.success()', /home/mark/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/9a6d8fc/build.rs:177:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: build failed


 stdout=
```

**Comment by SimonSapin** [comment]
Semi-recently we’ve had to add the `llvm-tools-preview` component but only for old-style compiler plugin (the custom lint) in the `script_plugins` crate, not for the `mozjs` crate. So this might not be relevant if you’re disabling the plugin crate entirely.

Our CI has the `clang`, `llvm`, and `llvm-dev` Ubuntu packages installed:

* https://github.com/servo/servo/blob/fde47f8937/etc/taskcluster/docker/base.dockerfile
* https://github.com/servo/servo/blob/fde47f8937/etc/taskcluster/docker/build.dockerfile

**Comment by nnethercote** [comment]
Probably want to update the code to get https://github.com/servo/servo/pull/27063, which was another big reduction in LLVM IR size.

**Comment by eddyb** [comment]
> The `script-servo` benchmark is about 3 years old, and recently a change took place that reduced the amount of generated LLVM IR from 10.2M lines to 7.2M lines, by avoiding bloat for one crucial function: [servo/servo#26585](https://github.com/servo/servo/issues/26585)
> 
> With that in mind it might be a good time to retire `script-servo` and introduce `script-servo-2`. It's not one of the "stable" benchmarks so there should be no problem with this.

Why would we change the benchmark? That means we'll no longer be measuring anything that reduces that bloat, such as MIR optimizations or (as it turned out to be the case), polymorphization.

I thought we kept benchmarks as unchanged as we could on `perf.rust-lang.org` so the data has meaning across time.

**Comment by nnethercote** [comment]
Several benchmarks are now on their second or later versions `ctfe-stress-4`, `hyper-2`, `script-servo-2`. I view it as a "living" benchmark suite. The exception is the "stable" subset, which feeds into the per-release measurements [here](https://perf.rust-lang.org/dashboard.html).
