### ISSUE TITLE
update to bumpalo 3.2.1

### ISSUE THREAD

**Issue by flipchan** [rust-lang/rustc-perf#667]
Bumpalo version less then 3.2.1 is unstable, please update Cargo.toml from 3.2 to 3.2.1

Links:
https://rust.firosolutions.com/paste/JBpDGtwKz6nMddFEux0TcFPROziA0jHpFBXcoK4w
https://rustsec.org/advisories/RUSTSEC-2020-0006.html

**Comment by Mark-Simulacrum** [comment]
I *think* this shouldn't affect perf since we don't call realloc (and copying bytes would be unsound for perf's use case, so if that does happen "woops"). But I'll take a look at doing this soon regardless.

**Comment by flipchan** [comment]
awesome! update version number and  close this when done
