### ISSUE TITLE
Can't compare results of `bench_local` in browser

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rustc-perf#668]
It looks like `compare.html` only works with commit SHA, which are not used when comparing two local `rustc` builds via `bench_local`

**Comment by nnethercote** [comment]
Have you tried following the [docs](https://github.com/rust-lang/rustc-perf/tree/master/collector/README.md)? As they say, a user-specific identifier can substitute for the SHA. I've done it many times myself.

**Comment by Aaron1011** [comment]
@nnethercote: I did follow the docs - however, I was unable to get it to work on the latest `master`

**Comment by Mark-Simulacrum** [comment]
Can confirm that this is broken; I'm working on a fix now.

**Comment by Mark-Simulacrum** [comment]
Pushed fix in 8b9654f27c292f3a2d36e911070402006b8d99a8 and 6350892eb98042b07bae260d917d83d503ad4f34. You will likely need to recollect data.
