### ISSUE TITLE
Support running a subset of available benchmarks

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rustc-perf#669]
Currently, `collector` always runs all benchmarks in the `benchmarks` directory. It would be useful to have a command-line flag to specify which benchmarks should be run, to avoid needing to move directories in and out of the `benchmarks` directory.

**Comment by Mark-Simulacrum** [comment]
There's a `--filter` flag which lets you provide a substring filter; we don't support more advanced filtering right now. If you have a specific desire then we can explore that (there's also profile flags that can specify not all profiles etc)

**Comment by nnethercote** [comment]
There's also `--exclude` for excluding, which works the opposite to `--filter`.
