### ISSUE TITLE
Cannot view self-profile data for `local_bench` result

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rustc-perf#670]
With https://github.com/rust-lang/rustc-perf/issues/668 fixed, I can now load the comparison page for two `local_bench` runs. However, I cannot view the detailed self-profile data, as `handle_self_profile` only looks for commits:

https://github.com/rust-lang/rustc-perf/blob/6350892eb98042b07bae260d917d83d503ad4f34/site/src/server.rs#L673-L681

**Comment by Mark-Simulacrum** [comment]
Fixed by 8d9ecf20.
