### ISSUE TITLE
Add testing of local benchmarking and profiling

### ISSUE THREAD

**Issue by nnethercote** [rust-lang/rustc-perf#681]
Local benchmarking and profiling commands periodically get broken by changes. This doesn't get caught because we don't have any tests for those commands.

We should add some tests, but I'm not quite sure what the tests would look like. They seem like they would be more complicated than normal Rust unit tests, because they have to invoke `rustc-fake`, `perf`, other profilers, etc.

**Comment by Mark-Simulacrum** [comment]
I imagine we can add some builders to CI which "benchmark" downloaded toolchains (but not using the bench_commit infra directly).

We should be able to make those runnable via normal Cargo integration tests which run our binaries - I believe cargo sets some environment variables for the various binaries of any given workspace (or crate? not sure).

**Comment by nnethercote** [comment]
All done.
