### ISSUE TITLE
Command options are a mess

### ISSUE THREAD

**Issue by nnethercote** [rust-lang/rustc-perf#683]
Here is a summary of all the commands and their options.
```
# benchmark a bors merge from AWS
- collector
  --filter $FILTER    [optional]
  --exclude $EXCLUDE  [optional]
  --db $DB            [mandatory]
  --self-profile      [optional]
  bench_commit
  $HASH               [mandatory]

# benchmark a local rust
- collector
  --filter $FILTER    [optional]
  --exclude $EXCLUDE  [optional]
  --db $DB            [mandatory]
  --self-profile      [optional]
  bench_local
  --rustc             [mandatory]
  --rustdoc           [mandatory for `Doc` builds]
  --cargo             [mandatory]
  --builds            [optional]
  --runs              [optional]
  $ID

# bench an artifact from static.r-l.o
- collector
  --filter $FILTER    [optional] [unused?]
  --exclude $EXCLUDE  [optional] [unused?]
  --db $DB            [mandatory]
  --self-profile      [ignored]
  bench_published
  $ID                 [mandatory]

# syncs to git and collects performance data for all versions
- collector
  --filter $FILTER    [optional] [unused?]
  --exclude $EXCLUDE  [optional] [unused?]
  --db $DB            [mandatory]
  --self-profile      [optional]
  process

# profile a local rustc
- collector
  --filter $FILTER    [optional]
  --exclude $EXCLUDE  [optional]
  --db $DB            [mandatory]
  --self-profile      [ignored]
  profile
  --output            [mandatory]
  --rustc             [mandatory]
  --rustdoc           [mandatory for `Doc` builds]
  --cargo             [mandatory]
  --builds            [optional]
  --runs              [optional]
  $PROFILER           [mandatory]
  $ID                 [mandatory]

# remove data for a benchmark
- collector
  --filter $FILTER    [ignored]
  --exclude $EXCLUDE  [ignored]
  --db $DB            [mandatory]
  --self-profile      [ignored]
  remove_benchmark
  --benchmark         [mandatory]

# test benchmark the most recent commit
- collector
  --filter $FILTER    [optional]
  --exclude $EXCLUDE  [optional]
  --db $DB            [mandatory]
  --self-profile      [optional] [unused?]
  test_benchmarks
```
Problems with this:
- The `remove_errs` command is unimplemented!
- The global options (`--filter`, `--exclude`, `--db`, `--self-profile`) aren't
  really global. They only apply to some commands.
- Many "options" aren't actually optional.
- Specifying `rustc`, `cargo` and `rustdoc` executables separately is a pain,
  and can lead to inconsistent combinations.

Suggested improvements:
- Remove `remove_errs`.
- Remove any other commands that aren't regularly used.
- Rename `--filter` as `--include`, to match `--exclude`
- Replace `--rustc`/`--cargo` with a single flag (`--bin`?) that names a
  directory that holds both executables (plus `rustdoc`). Or maybe just
  drop `--cargo` and use whatever `cargo` is in the PATH.
- Change the global options to command options, but only for the commands where
  that makes sense.
- Change all mandatory options into positional arguments. For example, the old
  command `collector --db $DB bench_local --rustc $RUSTC --cargo $CARGO $ID`
  would become `collector bench_local $DB $RUSTC $CARGO $ID`. (FWIW, I have
  some bash functions that I always use to run these commands, and they use
  positional arguments heavily.)

**Comment by nnethercote** [comment]
@Mark-Simulacrum:
- I know all about `bench_local` and `profile`.
- `test_benchmarks` is used with a `--db temporary.db` option in `ci/check-benchmarks.sh`, which is run via GitHub Actions.
- But I don't know how the others are used: `bench_commit`, `bench_published`, `process`, `remove_benchmark`. Do you run them manually? Are they run on CI? What options/arguments do they need?

**Comment by Mark-Simulacrum** [comment]
bench_published and process are the only two used on the collection server, for benchmarking stable/beta releases and the normal "run loop" of try/master commits.

bench_commit and remove_benchmark seem extraneous -- remove_benchmark should be done in the DB directly, pretty easily (just drop the name from the crates table), and bench_commit can be done with profile/bench_local after rustup-install-toolchain-master on the relevant commit.

**Comment by nnethercote** [comment]
How are `bench_published` and `process` invoked? I can't see any invocations in this repo. Is it from code outside this repo?

**Comment by Mark-Simulacrum** [comment]
Yes, though I can add it here without too much trouble. Will do so tomorrow.

**Comment by nnethercote** [comment]
The description for `process` is "Syncs to git and collects performance data for all versions". Is that correct? It looks like it only benchmarks a single revision.
