### ISSUE TITLE
Doc build failed on 1.45.0

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rustc-perf#696]
The beta run succeeded, but 1.45.0 was unable to be benchmarked. I suspect this is because of https://github.com/rust-lang/cargo/pull/8449.

**Comment by Mark-Simulacrum** [comment]
I'm inclined to just skip rustdoc perf collection for 1.45.0 entirely (probably a temporary patch in the code that does so), but wanted to file an issue in case people have other thoughts.

cc @jyn514

**Comment by jyn514** [comment]
Ah, I didn't realize you used the cargo from the release. Then yes, this will probably fail on all versions before https://github.com/rust-lang/cargo/pull/8449 and after --document-private-items was added to `cargo doc` (not sure when that was).

You could still make it work by using the latest nightly cargo, but I don't know if that's worth the effort.
