### ISSUE TITLE
multi-factor UI performance improvements

### ISSUE THREAD

**Issue by leeoniya** [rust-lang/rustc-perf#742]
hi Rustaceans,

i'm the author of https://github.com/leeoniya/uPlot and long-time Mozilla fan.

i noticed that https://perf.rust-lang.org/ currently uses Highcharts, and was curious to see how much of a difference uPlot could make to the page load times and general browser responsiveness and laptop battery life :)

the preliminary results are pretty stark. some highlights:

1. ~6x factor reduction in cpu, gpu, GC pressure
2. peak and retained JS heap usage drops from 149MB/149MB to 7MB/4MB
3. interaction performance with charts does not turn my laptop into a li-ion jet engine
4. a part of these improvements involves replacing msgpack with plain JSON and vastly reducing the current 6.7MB binary non-compressable payload to a more reasonable 1.09MB JSON gzip-able payload. (these changes will need to be done by the rustc-perf team, since i am not familiar with rust and my time is rather limited at the moment to learn it for this task).

**current:**

![rustc-perf-highcharts](https://user-images.githubusercontent.com/43234/89438887-ff3e2c00-d70e-11ea-9688-97315b6c93a1.png)

**uPlot:**

![rustc-perf-uplot](https://user-images.githubusercontent.com/43234/89438883-fea59580-d70e-11ea-8724-e1c132a03302.png)

before submitting a PR and doing additional work, I wanted to open this feeler thread to see if you guys were open to accepting UI performance improvements into this repo. i've previously submitted a similar issue to the firefox perf team, but they decided not to rock the boat: https://github.com/mozilla-frontend-infra/firefox-performance-dashboards/issues/293

cheers!
Leon

cc @Mark-Simulacrum @nnethercote

**Comment by Mark-Simulacrum** [comment]
I'm definitely open to switching the library out. Our main needs from the library are that there is some way to have clicking a point on the lines open a new page and per-point tooltips, with both ideally being generated on demand (we can have a lot of points). Beyond that we're pretty much ready to use anything.

I am also happy to do the legwork if a library meets these baseline requirements to experiment with a migration!

**Comment by leeoniya** [comment]
ok, sounds good.

> Our main needs from the library are that there is some way to have clicking a point on the lines open a new page and per-point tooltips

yes, both should be easily doable.

so, i guess we can do this in 2 stages. i'll leave the msgpack as-is and add a transformer into the structure i expect. then you can poke the backend to return that same JSON and ditch msgpack + transformer?

**Comment by Mark-Simulacrum** [comment]
https://gist.github.com/Mark-Simulacrum/3d749ab55d63bbd6f5874618f6749e58 is a diff of switching to JSON. That does bump up our graph endpoint from 7MB to 11MB (we don't currently compress at all); you have vastly different results here though?

> a part of these improvements involves replacing msgpack with plain JSON and vastly reducing the current 6.7MB binary non-compressable payload to a more reasonable 1.09MB JSON gzip-able payload. (these changes will need to be done by the rustc-perf team, since i am not familiar with rust and my time is rather limited at the moment to learn it for this task).

Maybe I've misinterpreted what you're saying.

**Comment by Mark-Simulacrum** [comment]
But your steps sound good to me. Feel free to ping me on the rust-lang Zulip as well, https://rust-lang.zulipchat.com/#narrow/stream/247081-t-compiler.2Fperformance works well.

**Comment by leeoniya** [comment]
> That does bump up our graph endpoint from 7MB to 11MB (we don't currently compress at all); you have vastly different results here though?

right, the raw decompression is 11MB, but it's full of redundancy. all the timestamps are in ms, but are just unix timestamps, so they can all lose the trailing 000. the timestamps are all aligned per commit, so they dont need to be repeated for every dataset, but there only need to be 155 of them in total. the "percentage" can be calculated on-demend in the browser and does not need t obe present in the data. "is_interpolated" seems useless, as does the y coordinate. the only real y data is the "absolute".

once all of this is cleaned up, you end up with ~1MB.

**Comment by Mark-Simulacrum** [comment]
Sounds great :)

Yeah, the current data format was mostly organically grown over time, adding fields as they became necessary in the UI client-side without too much care about the data size. 1MB of data after all of that sounds quite reasonable.

FWIW the timestamps would be fine to downgrade to minute precision (or even like 5 minute precision). I guess if we deduplicate that doesn't matter anymore though.

**Comment by leeoniya** [comment]
heh, i didn't realize you guys weren't rendering the `-doc` charts from the returned dataset; with those removed from the uPlot version, the improvement is ~10x.

as far as variable/key naming...i see that the chart series names are "cache states": https://perf.rust-lang.org/compare.html, so i'll use something like `for (let cacheState in ...) `. what's the proper rust-land term for `doc`, `opt`, `debug`, `check`? some wild guesses: `build`, `buildCmd`, `buildKind`, `buildType`, `optLevel`, `level`, `profile`?

Highcharts appears to use `G` for denoting tick labels for billions but i'm leaning towards using `B`, unless there's some logic behind this?

also, what are the pink diamond datapoints in the Summary charts?

**Comment by nnethercote** [comment]
> what's the proper rust-land term for `doc`, `opt`, `debug`, `check`?

These are `buildKind`s.

> Highcharts appears to use `G` for denoting tick labels for billions but i'm leaning towards using `B`, unless there's some logic behind this?

Either you want the abbreviation for the SI prefix (K for kilo, M for mega, G for giga) or the abbrevation for the number name (T for thousand(?), M for million, B for Billion). In practice all our numbers are millions or billions, so it probably doesn't matter much either way.
 
> also, what are the pink diamond datapoints in the Summary charts?

They mean "something went wrong". E.g. when looking at the chart for a single benchmark, it failed to measure somehow, e.g. because of a compile error. For script-servo-2 there are currently "failures" because that benchmark was removed. And for the summary graphs, pink diamonds will show up if there's a failure in any of the individual benchmarks.

If you have valid results followed by some failures followed by more valid results, the system does its best to interpolate pink diamonds across the stretch of no results.

**Comment by leeoniya** [comment]
> These are buildKinds.

👍 

> Either you want the abbreviation for the SI prefix (K for kilo, M for mega, G for giga)

ah, right. G it is. unless you want to go prefix-free with e.g. `4.5e6`.

> They mean "something went wrong"

ok, i'll see when i get to that. likely will have more questions. might need to be done as annotations (#666).

here's my WIP so far, including the data as a js `const`: [rustc-perf-uplot-0.zip](https://github.com/rust-lang/rustc-perf/files/5032992/rustc-perf-uplot-0.zip)

i'll see about tooltips tomorrow:

https://leeoniya.github.io/uPlot/demos/tooltips.html
https://leeoniya.github.io/uPlot/demos/candlestick-ohlc.html

**Comment by nnethercote** [comment]
I prefer `M` and `G` to `e6` notation.

**Comment by leeoniya** [comment]
did a bit of work on the tooltips, which are coming along well. should have a PR ready in next couple days, time permitting.

meanwhile, below is what i'm thinking for the JSON response structure. also, do you think it'd be useful to also pull the commit message into the tooltip? this seems logical to me so i've included it in the structure below if you feel like appending it.

```js
{
  "commits": [
    [1594068256, "8981dbbc36f1575b0a417b6849767bde29e7c6b4", "Shrink ParamEnv to 16 bytes"],
    [1594083404, "70f9d23b916f2db7da711aa4a0317a218997ba42", "Rollup of 14 pull requests"],
  ],
  "benchmarks": {
    "regression-31157": {                       // benchName
      "check": {                                    // buildKind
        "full": [719798144, 719807680, ...],            // cacheState: y-values
      }
    },
  }
}
```

would it be possible for your guys to create a JSON endpoint for me to test against with open CORS headers (and maybe gzip ;) so i can run test fetches against the live db from my `localhost:8080`. that would be a significant quality-of-life improvement for me. if not, i'll just keep curling and massaging the binary msgpack responses, but this is somewhat of a nuisance.

**Comment by Mark-Simulacrum** [comment]
We don't have the commit messages on hand right now, and only have PR numbers as of a few days ago. Probably we just want to stick to commits for now.

**Comment by leeoniya** [comment]
is there any way for me to test the frontend changes against an existing live backend without having to download the 3.8GB database or run the backend locally?

as mentioned above:

> would it be possible for your guys to create a JSON endpoint for me to test against with open CORS headers (`Access-Control-Allow-Origin: *`) and maybe gzip ;) so i can run test fetches against the live db from my `localhost:8080`.

**Comment by Mark-Simulacrum** [comment]
I can work on preparing a JSON endpoint like you've described today, or if your changes are compatible with the current master code, I think you can modfiy https://github.com/rust-lang/rustc-perf/blob/0bad4095a502efe2213676999e53f223a1c8d409/site/static/shared.js#L1 to point at perf? Though we don't set Access-Control-Allow-Origin headers right now, so maybe that'll need to be changed for that to work, not sure. I'm open to doing so...

**Comment by Mark-Simulacrum** [comment]
Okay, that turned out to be a bit easier than I expected. `perf.rust-lang.org/perf/graph-new` is the endpoint, with the return being JSON (no gzip currently, though we can add it later transparently I imagine); it should have the CORS header set to *.

The returned JSON is represented by [these structs](https://github.com/rust-lang/rustc-perf/blob/5a1f9289cfd5fa40c44aae18d70adeee589a370f/site/src/api.rs#L142-L155) and should pretty closely match what you had. I did add the interpolation atop what you had -- that's necessary for the graph page.

**Comment by leeoniya** [comment]
thanks, i'll try it out in a bit.

also, should these routes be GET routes? i'm not sure why POST is used currently since they don't cause server-side mutation (idempotent) and are perfectly/safely bookmarkable.

**Comment by leeoniya** [comment]
i switched to `no-cors` mode to get the request working:

```js
return fetch(BASE_URL + path, {
  method: "POST",
  body: JSON.stringify(body),
  mode: "no-cors"
}).then(response => {
```

i'm getting `response.ok: false`, though the response headers are showing a content-length, but i don't see the network tab showing that amount of payload transferred (only 14.4kb).

![resp](https://user-images.githubusercontent.com/43234/89712770-ac57b500-d958-11ea-955b-1335766b2829.png)

**Comment by Mark-Simulacrum** [comment]
`curl -sSL -vv -X POST -d '{"stat":"instructions:u","start":"","end":"","absolute":true}' https://perf.rust-lang.org/perf/graph-new --output /tmp/o` works fine for me locally, gives me:

```
< HTTP/2 200
< date: Sat, 08 Aug 2020 14:31:32 GMT
< content-type: application/json
< content-length: 1695142
< cache-control: no-cache, no-store
< access-control-allow-origin: *
```

which is ~1.7MB.

**Comment by Mark-Simulacrum** [comment]
I think we only use POST because I wasn't sure about GET requests with JSON bodies -- we could likely use query parameters, but the current backend makes decoding those a little bit more annoying (though not insurmountable, we should likely switch).

**Comment by leeoniya** [comment]
can you please try running an actual `fetch` in a browser from `localhost`? curl doesn't really need to care about respecting any of that browser security nonsense. it's probably failing due to some cors-related stuff, but failing nonetheless.

**Comment by Mark-Simulacrum** [comment]
```
fetch("https://perf.rust-lang.org/perf/graph-new", { method: "POST", mode: 'no-cors', headers: { 'Content-Type': 'application/json' }, body: '{"stat":"instructions:u","start":"","end":"","absolute":true}' })
```

This seems to work fine for me in Firefox.

**Comment by leeoniya** [comment]
odd. i'm running this in the firefox console and getting `false`:

```
fetch("https://perf.rust-lang.org/perf/graph-new", { method: "POST", mode: 'no-cors', headers: { 'Content-Type': 'application/json' }, body: '{"stat":"instructions:u","start":"","end":"","absolute":true}'}).then(r => console.log(r.ok));
```

**Comment by Mark-Simulacrum** [comment]
Hm okay I'm also seeing that on localhost (I was previously testing on an IP page, 192.168.1.220:2346). That feels pretty weird to me...

**Comment by Mark-Simulacrum** [comment]
I think the problem might be the pre-flight OPTIONS request. I've modified the code a bit and pushed up a new version (should deploy in ~11 minutes).

**Comment by leeoniya** [comment]
ok, we're back in business. thanks!

`is_interpolated` looks unsorted, btw. shouldn't make much difference in real life since it'll just be ingested by `new Set()`, but would make reviewing the raw data easier.

**Comment by leeoniya** [comment]
#744 is where i ended up. there's enough there to review and move forward from.

due to lack of time, i'm not going to be able to get this into a final state, but i'll be available to answer additional questions if you guys choose to pursue this further.
