### ISSUE TITLE
can't reset graph zoom level

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rustc-perf#746]
When zooming in on an instr-count graph for example, I no longer see a way to reset the zoom level to default values. I think this worked in the previous version (there was a little button in one of the corners iirc).

**Comment by Mark-Simulacrum** [comment]
You need to double click, but this is really non-obvious. Probably we should just add a always-shown hint to the top of the page or something...

**Comment by matthiaskrgr** [comment]
Hm, this works *sometimes* but in most cases firefox' cpu usage just ramps up to 100% until firefox offers to kill the tab without any visible effects on the actual page :/

**Comment by leeoniya** [comment]
might be easier to just add  zoom reset button as in the previous version. the doubleclick also won't work when a series is focused, since clicking once takes you to the commit diff.

**Comment by Mark-Simulacrum** [comment]
@leeoniya Any ideas on what could be causing the 100% cpu problem?

**Comment by leeoniya** [comment]
i've never been able to trigger the 100% CPU behavior on zoom reset. steps for deterministic repro would obviously help.

**Comment by matthiaskrgr** [comment]
I can sometimes reproduce it by clicking on a graph repeatedly while moving the cursor out of the plotting area while doing so.

**Comment by leeoniya** [comment]
does this also happen in Chrome? can it be triggered on all graphs or only graphs with certain properties like null datapoints, etc. maybe some mouse gestures Firefox extension is causing this. maybe try with a clean profile. i'm really out of ideas.

do you have a screen recording that shows click points and how you're moving the mouse?

without a reduced repro and/or a lot more details this is unlikely to be found/fixed, as i cannot repro it myself.

@Mark-Simulacrum have you been able to trigger this?

**Comment by matthiaskrgr** [comment]
I am able to reproduce on chromium as well, resulting in a `Fix "Aw, Snap!" page crashes and other page loading errors` error being shown.
I'll try to get some kind of screencap done somehow..

**Comment by leeoniya** [comment]
can you trigger it on any charts below? if so, which?

https://leeoniya.github.io/uPlot/demos/zoom-variations.html

**Comment by leeoniya** [comment]
ok, thanks. the recording helped and i was able to trigger this.

looks like it was a precision issue that caused an infinite loop when the determined tick spacing value was too small. i've pushed a couple commits that bail out of zooming above a max tick & grid resolution. try swapping in uPlot `master` and see if that fixes it:

https://raw.githubusercontent.com/leeoniya/uPlot/master/dist/uPlot.iife.min.js

**Comment by Mark-Simulacrum** [comment]
Pushed up a commit swapping out the JS, should deploy in ~10 minutes.

**Comment by leeoniya** [comment]
heh, merged a bit too soon :)

now there's some some y axis tick formatting issues due to precision foo. i'm working through that right now.

for now i worked around it in the value formatter, but this is not ideal:

```js
values: (self, splits) => {
    return splits.map(v => {
        return (
            v >= 1e12 ? uPlot.fmtNum(v/1e12) + "T" :
            v >= 1e9  ? uPlot.fmtNum(v/1e9)  + "G" :
            v >= 1e6  ? uPlot.fmtNum(v/1e6)  + "M" :
            v >= 1e3  ? uPlot.fmtNum(v/1e3)  + "k" :
            uPlot.fmtNum(v)
        );
    });
},
```

then i'll tackle #749.

**Comment by leeoniya** [comment]
pushed some more commits which should fix the remaining issues.

**Comment by rylev** [comment]
I believe this issues discussed here have been fixed. If that's not the case, we can open a new issue.
