### ISSUE TITLE
Relative graphs do not display data below 0%

### ISSUE THREAD

**Issue by ecstatic-morse** [rust-lang/rustc-perf#747]
Graphs of relative benchmark performance are cut off below 0, so any total improvements [are not displayed](https://perf.rust-lang.org/?start=8b84156c6ee2b4e707dc32f5a516e3143ab924d3&end=67e7b9b8cf776222825dbbd4cb1e39b7765ef27c&absolute=false&stat=instructions%3Au).

**Comment by leeoniya** [comment]
looks like the `0` passed to `rangeNum` needs to be conditioned on the relative/absolute mode:

https://github.com/rust-lang/rustc-perf/blob/e235e5fbf7ca66e4540d79d66be467d3acb44bb1/site/static/index.html#L185-L187

**Comment by Mark-Simulacrum** [comment]
Fixed by 531667321437d1ac684b8533bce0463a45b36ce0, thanks!
