### ISSUE TITLE
Collector fails if `LC_MEASUREMENT` is not set to English

### ISSUE THREAD

**Issue by Kobzol** [rust-lang/rustc-perf#753]
Hi! I wanted to try to run the `rustc-perf` collector and I hit a very peculiar error. On my notebook, the `LC_MEASUREMENT` locale is set to Czech (my native language) and not to English. This in turn causes `perf stat` to output floating point numbers with a comma (`100,0`) instead of a dot (`100.0`), which causes the collector to fail in various places with errors like:
```
thread 'main' panicked at 'measurement of `instructions:u` only active for 100,00% of the time', collector/src/execute.rs:1307:13
```

Honestly I have no idea how I even realized that this is the problem, as I was almost tearing my hair out. So I wondered if you could maybe include this in some FAQ section in the README, if anyone else also hits the same problem? I'll send a PR if you think that it's a good idea.

**Comment by Mark-Simulacrum** [comment]
Do you know if there's a reason for perf not to override this to "C"? Presumably that would be cross-platform compatible.

I wasn't even aware of the existence of this environment variable or that perf read it :)

**Comment by Kobzol** [comment]
No idea, I also didn't know about its existence. The collector was failing and I found out that it is caused by the weird formatting. Then I ran `locale` and it outputted amongst other things `LC_MEASUREMENT`, which looked suspicious, so I tried to change it and it fixed the issue. Maybe it's not perf that directly reads it, but some other formatting library that it uses?

I don't even know why it's set to Czech, my computer is otherwise in English (`LANG`, `LANGUAGE`, etc. are English), I just have a Czech timezone and for some reason that apparently translates to Czech-formatted `perf` results :)

I just wanted to share this if anyone else stumbled upon this, since it's a pretty annoying problem (I couldn't find anything on Google and couldn't get the collector to run).

**Comment by Mark-Simulacrum** [comment]
41298173 should fix this for you, hopefully -- let me know if not.

**Comment by Kobzol** [comment]
Thank you! Sadly, the flag that you have used doesn't work :( (this locale stuff is crazy):
- `LC_MEASUREMENT=C` doesn't work
- `LC_MEASUREMENT=en_US` works
- `LC_NUMERIC=C` works
- `LC_NUMERIC=en_US` works
I really don't want to investigate why it behaves like this.
Setting `LC_NUMERIC=en_US`, `LC_NUMERIC=C` or even `LC_ALL=en_US` should hopefully do the job.

**Comment by Mark-Simulacrum** [comment]
Gah, okay. I'll modify it to LC_NUMERIC=C later today then. I would prefer to avoid en_US because I suspect that might break if users don't have that locale installed, for example if they have en_GB instead or just no English locale at all.

**Comment by Kobzol** [comment]
That makes sense. I changed it here: https://github.com/rust-lang/rustc-perf/pull/754.
