### ISSUE TITLE
TRIAGE: Fetch PR titles when generating the weekly report

### ISSUE THREAD

**Issue by ecstatic-morse** [rust-lang/rustc-perf#767]
We already have the PR number from `rustc-perf`, so all you need to do is call out to the GitHub API at the appropriate part of the triage report generator. It should be added after the first part of `msg`:

https://github.com/rust-lang/rustc-perf/blob/6c66c38952efdc553cfa925f5bb72788fea302ab/triage/weekly_report.py#L180-L184

**Comment by ecstatic-morse** [comment]
@Mark-Simulacrum Not sure how often people look for issues in this repo, but I meant for this to be a contribution opportunity. Can you label it as such?

**Comment by Mark-Simulacrum** [comment]
Probably not very often, but labeled as such. I would be happy to add triagebot btw, just not something I've gotten around to. Feel free to send a PR if you'd like.

**Comment by Horki** [comment]
@Mark-Simulacrum #809 please review

**Comment by Horki** [comment]
@Mark-Simulacrum thanks for merging, this can be closed now right?
