### ISSUE TITLE
Narrowing the layout of compare site

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rustc-perf#776]
The compare site has the submit button really far away from two commit text-boxes.
Can we make the submit button near the stat button ?
This way the mouse cursor doesn't have to move far away to reach submit button.

![image](https://user-images.githubusercontent.com/15225902/94786447-307b6580-03fb-11eb-9c74-b1c4974dba52.png)

Also, can we narrow down the width of layout ? About 800px ? We have a lot of unused blank spaces
in desktop screen.
![image](https://user-images.githubusercontent.com/15225902/94786885-c1524100-03fb-11eb-9cb5-f3d2ec1df93d.png)

**Comment by Mark-Simulacrum** [comment]
I would be happy to accept a PR.
