### ISSUE TITLE
Static files on the site does not have a Content-Type response header

### ISSUE THREAD

**Issue by Rob--W** [rust-lang/rustc-perf#784]
The perf.rust-lang.org site does not set the Content-Type response header. For example:
- https://perf.rust-lang.org/
- https://perf.rust-lang.org/favicon.svg
- https://perf.rust-lang.org/favicon-32x32.png

Probably need to choose a Content-Type based on the file extension at https://github.com/rust-lang/rustc-perf/blob/264009814a4d029f2bb8bb92050fbef18019e57f/site/src/server.rs#L1526-L1529

**Comment by CyberShadow** [comment]
@Mark-Simulacrum This is still a problem for the main page (https://perf.rust-lang.org/):

```
< HTTP/2 200 
< date: Fri, 05 Jan 2024 06:17:23 GMT
< content-length: 1627
< etag: "16cfeb3b-2065-4b25-a403-6fae182d85fe"
< cache-control: max-age=60, stale-while-revalidate=86400
< access-control-allow-origin: *
```
