### ISSUE TITLE
Downloading Profile Data From Detailed Query Page Fails with 500

### ISSUE THREAD

**Issue by rylev** [rust-lang/rustc-perf#790]
Visiting a detailed query page and trying to download the profile data in some form other than "raw" fails with a 500. 

**To Reporduce**
* Go to https://perf.rust-lang.org/detailed-query.html?commit=714be566bc534eb3fda0665a281f12b58ab61f0c&benchmark=externs-debug&run_name=incr-unchanged
* Click on one of the profile data links at the top of the page (e.g., "flamegraph")
* It will 500 

This does not seem to happen for all detailed query pages.

**Comment by lqd** [comment]
IIUC this is related to `rustc`'s recent update of `measureme`, whose format is not compatible with the previous format. The `analyzeme`, `crox` and `flamegraph` tools currently used in `rustc-perf` are using the older format. The goal of PR #788 is to make it possible to use either versions depending on the format of the recorded profile. 

Until that is completed, raw downloads still work (as they are not processed by the `analyzeme` tools) so you can, say, compute the flamegraph locally, but the flamegraph, crox json, and speedscope and FF profiler links on the detailed query pages won't work.

**Comment by Mark-Simulacrum** [comment]
Yep, that's correct. I've been busy with other projects these last few weeks unfortunately so haven't found the time to focus on this, but hopefully that'll clear up soon.

**Comment by tgnottingham** [comment]
Fixed by #978.
