### ISSUE TITLE
Indicate that keccak benchmark has high max-rss variance

### ISSUE THREAD

**Issue by tgnottingham** [rust-lang/rustc-perf#800]
This benchmark regularly varies by +/- 15% max-rss on any given perf run. This should be indicated somehow, so that changes aren't regarded as regressions/improvements when it's just variance. If we don't have per-statistic variance indications, perhaps it would be good to add them.

**Comment by Mark-Simulacrum** [comment]
All variance is just client side - it should be fairly straightforward to extend the ?? adding logic to support keccak. It might also be interesting to try to figure out why there's such a large variance.

**Comment by tgnottingham** [comment]
Since rust-lang/rust#83152, the wide swings in max-rss have disappeared. And we're doing more work to track variance in general now. Closing!
