### ISSUE TITLE
Add a way to overwrite benchmarks

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rustc-perf#804]
Maybe `--force`? My use case is that I made changes to `collector` because it was buggy, but now it refuses to collect the new benchmark because it has the same name as the old one.

For now, I'm just deleting `results.db` but it would be nice to not have to throw out *all* the old data I collected.

**Comment by Mark-Simulacrum** [comment]
cc https://github.com/rust-lang/rustc-perf/pull/752
