### ISSUE TITLE
Show total bootstrap time

### ISSUE THREAD

**Issue by tmiasko** [rust-lang/rustc-perf#813]
The "bootstrap timings" section should show overall build time.

**Comment by Mark-Simulacrum** [comment]
Added, but note that the time is right now -j1 so not really representative of most computers. But still useful - e.g. the PGO patch ended up decreasing total time by 2.3% which is overall not that much, though it did cut 30ish seconds from the total build.

**Comment by tmiasko** [comment]
Thanks!
