### ISSUE TITLE
Add summary to 'Finished benchmarking' bot comment

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rustc-perf#817]
It would be useful for comment to list the maximum improvement and maximum regression, along with the corresponding benchmark names.

**Comment by Kobzol** [comment]
The PR comment has been heavily reformed and now shows range of both improvements and regressions. I think that benchmark names are too detailed for the comment, which already contains a myriad of information. Therefore, I think that this issue can now be closed. Feel free to reopen if you don't agree.
