### ISSUE TITLE
deeply-nested benchmark is troublesome for LLVM

### ISSUE THREAD

**Issue by tmiasko** [rust-lang/rustc-perf#823]
The deeply-nested benchmarks have at various times in the past exposed a performance bug in LLVM. Depending on inlining decisions and unit partitioning the compilation might require a few orders of magnitude more time to complete than usual:

* https://github.com/rust-lang/rust/pull/77307#issuecomment-711030328
* https://github.com/rust-lang/rust/pull/66329#issuecomment-568947987
* https://github.com/rust-lang/rust/pull/68213#issuecomment-574596287
* https://github.com/rust-lang/rust/issues/70749

Consider changing the benchmark to avoid the issue (e.g., use a single codegen unit) or removing the benchmark altogether.

**Comment by Mark-Simulacrum** [comment]
This seems like precisely the reason to not change the benchmark - we don't want user code to hit this. If there's an LLVM bug we should fix that directly.

**Comment by tmiasko** [comment]
> This seems like precisely the reason to not change the benchmark - we don't want user code to hit this. If there's an LLVM bug we should fix that directly.

Right, bug impacts users right now and should be fixed (see other examples in linked thread that expose it right now).

Exposing it in this benchmark is a matter of simplifying the IR enough to change inlining decision in LLVM (while keeping empty and chain in separate codegen unit). It isn't indicative whether problem is present in general or not, so keeping it as is is mostly a source of trouble with little benefits, especially that benchmarks is completely artifical (chaining empty iterators of ZSTs).
