### ISSUE TITLE
Consider removing or replacing the avg stat on the compare page

### ISSUE THREAD

**Issue by tgnottingham** [rust-lang/rustc-perf#843]
The `avg` stat on the compare page is a bit misleading. It's an average of percentages, each given equal weight, for different categories of results (full, incr-full, etc.), which doesn't make a ton of sense. It means, for example, that incr-full and incr-unchanged have equal weight in the average. And it means that incr-comp is really heavily weighted in the average since we often have 3 or more incr-comp results to the one non-incr-comp result.

I think it should be removed or replaced. Removing it may be the right call, because each of the build types really should be considered individually when evaluating a PR, and a single number is only going to make it easier to ignore a regression in one type of build when the single number improved.

But if a single number is strongly desired, you could do something like sum the values (e.g. instructions) across all build types (runs) in the benchmark, and then compare those before and after to come up with a percentage change. This might be described as the "total" change or something. Of course, this effectively causes the number to more heavily weight full and incr-full, but that makes a bit more sense.

**Comment by rylev** [comment]
Closing this as we no longer show the avg on the comparison page.
