### ISSUE TITLE
500 internal error loading firefox profile data

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rustc-perf#851]
https://perf.rust-lang.org/perf/processed-self-profile?commit=36f1f04f18b89ba4a999bcfd6584663fd6fc1c5d&benchmark=keccak-opt&run_name=full&type=crox/marker-chart/?v=5 is a 500. I got there from the [detailed self-profile view](https://perf.rust-lang.org/detailed-query.html?commit=33fa9f15639c420e2e76b65192553337d67a7e0a&base_commit=36f1f04f18b89ba4a999bcfd6584663fd6fc1c5d&benchmark=keccak-opt&run_name=full) -> ['Firefox profiler'](https://profiler.firefox.com/from-url/https%3A%2F%2Fperf.rust-lang.org%2Fperf%2Fprocessed-self-profile%3Fcommit%3D33fa9f15639c420e2e76b65192553337d67a7e0a%26benchmark%3Dkeccak-opt%26run_name%3Dfull%26type%3Dcrox/marker-chart/?v=5)

**Comment by Mark-Simulacrum** [comment]
Yeah, the self-profile summary views currently don't work; we need to migrate to the new profile format in the frontend. You can download the raw file though and that should work.

**Comment by jyn514** [comment]
> the self-profile summary views currently don't work; 

I'm confused - the summary view works fine:
![image](https://user-images.githubusercontent.com/23638587/111681997-3d99de80-87fa-11eb-872e-7d0c8d9f20b9.png)

It's just the 'processed-self-profile' page that doesn't work.

> You can download the raw file though and that should work.

Thanks, that gave me an .mm_profdata file, but it doesn't track memory usage (https://github.com/rust-lang/rust/issues/81348). Is there a way to see detailed memory usage other than with the 'max-rss' view? That only shows the total change, not what parts of the compiler changed.

**Comment by Mark-Simulacrum** [comment]
right, yes, I meant the processed ones.

To my knowledge we don't track memory usage on any fine-grained level (I guess other than time-passes, but that has it's own problems) in the compiler today, including on a per-query level in self-profile.

**Comment by tgnottingham** [comment]
Fixed by #978.

**Comment by jyn514** [comment]
Works great, thank you!
![image](https://user-images.githubusercontent.com/23638587/130296437-643b7886-038b-4fac-b5dd-1ced9dffd9b3.png)
