### ISSUE TITLE
Cannot profile local rustc

### ISSUE THREAD

**Issue by Nicholas-Baron** [rust-lang/rustc-perf#854]
I am trying to address the [rustc regression shown here](https://perf.rust-lang.org/compare.html?start=066f01d81bfbed746f6b6cf27a0426d829e8e832&end=b3ac52646f7591a811fa9bf55995b24fd17ece08&stat=instructions:u).
I have checked out the latest version of this repo and cannot use `profile_local`.
Build steps:
+ `rustc` with `./x.py b --stage 2 library/test`
+ `rustc-perf` with `cargo build` (same result with `--release`)

The following command will fail: 
```
./target/release/collector profile_local cachegrind ../rust/build/x86_64-unknown-linux-gnu/stage2/bin/rustc mine --include diesel
```
with this output:
```
Profiling with Cachegrind
1 benchmark remaining
Preparing diesel
Running diesel: Check + [Full, IncrFull, IncrUnchanged, IncrPatched]
collector error: Failed to profile 'diesel' with Cachegrind, recorded: failed to obtain pkgid in '"/tmp/.tmpZsNXtr"'

Caused by:
    No such file or directory (os error 2)
collector error: 1 benchmarks failed
```

**Comment by Mark-Simulacrum** [comment]
I wasn't able to reproduce this change after building same as you did - I wonder if you can check that `valgrind --tool=cachegrind echo` works for you... but it also looks like there's some error with a pkgid not resolving, not sure why that would be.

**Comment by tgnottingham** [comment]
@Nicholas-Baron Does this error still occur for you? Can you reproduce it with `RUST_LOG=trace`? Based on the output and inspection of the code, it kind of looks like the path to cargo that it's using internally points to some non-existent file. The logs should give us more of a clue.

**Comment by Nicholas-Baron** [comment]
@tgnottingham It seems to be work now. The profile is taking a long time, but that is expected with valgrind.
When it finishes, I will close this issue, as it seems to have been resolved.

**Comment by Nicholas-Baron** [comment]
Looks like it did work. Now time to interpret the results folder.
