### ISSUE TITLE
bechmark syn panics with ICE on rust-perf

### ISSUE THREAD

**Issue by klensy** [rust-lang/rustc-perf#858]
Bechmark `syn v0.11.11` panics with ICE on rust-perf last few days(weeks?), It can be seen at https://perf.rust-lang.org/status.html.

**Comment by Mark-Simulacrum** [comment]
The fix is being worked on by @Aaron1011 upstream (don't have a handy link right now).

**Comment by Aaron1011** [comment]
This is issue https://github.com/rust-lang/rust/issues/83538

**Comment by rylev** [comment]
This issue has been fixed (see https://github.com/rust-lang/rust/issues/83538)
