### ISSUE TITLE
Full name of `match-stress-exhaustive_patterns-check` is not shown on summary page

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rustc-perf#862]
![bad_perf_page](https://user-images.githubusercontent.com/1408859/113326204-5bca0900-92e7-11eb-8bc6-e2a4734cea56.png)

This is quite frustrating, as it makes it more difficult to reproduce the result locally.

**Comment by Mark-Simulacrum** [comment]
Hm, in the sense that check is not shown? I agree that seems unfortunate. The intent with truncating IIRC was to avoid taking up too much horizontal space, but if it's going to wrap to multiple lines I suspect we can show the 2 parts (name and check/opt/dbg/doc) on separate lines and just not try to be fancy here.

**Comment by rylev** [comment]
This issue has been fixed:

<img width="488" alt="Screenshot 2021-07-29 at 15 45 25" src="https://user-images.githubusercontent.com/1327285/127503196-158abcf4-1fbf-411b-bae1-a62ef76c91b7.png">
