### ISSUE TITLE
git apply unknown switch `N'

### ISSUE THREAD

**Issue by tmiasko** [rust-lang/rustc-perf#876]
From rustc-perf status page:

```
deep-vector - error

expected success, got exit code: 129

stderr=error: unknown switch `N'
usage: git apply [<options>] [<patch>...]
```

cc @wesleywiser

**Comment by bjorn3** [comment]
https://github.com/rust-lang/rustc-perf/pull/865/files#diff-a24d2de5fef556a353955db1c7125ed7916df8074f9094b909c1e6bd379a3aaeR1553

Unlike `patch` I don't think any option like `-N` is necessary for `git patch`.

**Comment by bjorn3** [comment]
`-p1` is also the default for `git patch`.

**Comment by tmiasko** [comment]
#877 should fix the git apply issue.

I was originally interested in results for calloc optimization. They look quite surprising not sure if the results are accurate of a side effect of this or another bug https://perf.rust-lang.org/compare.html?start=8d1e3d3b74fa80ce14af6ec143f061897684582b&end=ea78d1edf364dd3a4b5ff430f76e2bdd3a713a45&stat=instructions:u

**Comment by tmiasko** [comment]
With the git apply issue fixed there are now reverse perf results in https://perf.rust-lang.org/compare.html?start=e51830b90afd339332892a8f20db1957d43bf086&end=1c6868aa21981b37cbd3fc95828ee3b0ac22d494&stat=instructions:u , so it must have been related to this issue.

**Comment by lqd** [comment]
@Mark-Simulacrum do you think we need to clear and re-do the benchmarks for the commits which may have been skewed because of this ?

**Comment by Mark-Simulacrum** [comment]
I unfortunately don't have much time right now to do so -- I think ultimately it's fine if a few commits have a 'spurious' bump.
