### ISSUE TITLE
Finish documenting the database schema

### ISSUE THREAD

**Issue by rylev** [rust-lang/rustc-perf#903]
#899 started to document the [database schema](https://github.com/rust-lang/rustc-perf/blob/8e4d3e789679c355fdee87c3f6669261266380d4/database/schema.md) for parts I was working on. We should finish documenting the rest.

**Comment by bikash119** [comment]
hi rylev, I am fairly new rustacean. I want to pick this issue as its marked **E-easy**. Can you pls help me get started on this?

**Comment by rylev** [comment]
@bikash119 Thanks for your interest in helping. Unfortunately, we're actually thinking about doing some refactoring to the database (outlined in the issue #937), and so this actually should be put on hold until we finish that. I'm going to remove the `E-easy` label for now. 

Feel free to drop by [zulip](https://rust-lang.zulipchat.com/#narrow/stream/247081-t-compiler.2Fperformance), if you'd like to talk more about possible ways to help. I'll try to find other good issues for newcomers to the codebase to work on.

**Comment by Kobzol** [comment]
This has been done in https://github.com/rust-lang/rustc-perf/pull/1607.
