### ISSUE TITLE
Bench item build types mixed, if `Show only significant changes` selected

### ISSUE THREAD

**Issue by klensy** [rust-lang/rustc-perf#923]
Without checkbox `Show only significant changes`:

![pic_all](https://user-images.githubusercontent.com/1782831/126209310-2e896bc5-eff4-4a7b-bfa0-f388905e6d0c.png)

With checkbox:

![pic_sig1](https://user-images.githubusercontent.com/1782831/126209449-730e35d0-814e-4f7a-823c-eaa1b74194e7.png)

**Comment by klensy** [comment]
Looking at screenshot at #919, min-max values removed now.

**Comment by rylev** [comment]
This was fixed by #924.

Do you find the min-max values useful? I removed them since (with always expanded sections), it's not too useful. I personally always just ignore that information.

**Comment by klensy** [comment]
Not that i liked that min-max, but it was removed without explicit comment in unrelated commit, so i asked to be sure that this was intended.
