### ISSUE TITLE
Provide way to link to graphs

### ISSUE THREAD

**Issue by rylev** [rust-lang/rustc-perf#934]
We should provide a way to access the graphs page in a way that brings up only one of the benchmarks, or only a specified subset of the benchmarks. Preferably this would also provide a way to zoom the graphs to a certain subset of x and y axis ranges. 

One easy preliminary fix is to add anchor points so you can link to url#graph and the browser will scroll to the right graph automatically.

**Comment by Kobzol** [comment]
This is now possible: https://perf.rust-lang.org/index.html?start=2022-07-27&end=0fcc3f7cb58982a7dea6cdb52d99e258201f2cba&benchmark=helloworld&profile=check&scenario=incr-unchanged&stat=instructions:u. The links are generated on the compare page in the Profile column.
