### ISSUE TITLE
Anyone can crash rust-timer without permissions

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rustc-perf#936]
***Please do not actually do this.***

https://github.com/rust-lang/rustc-perf/blob/e8f5ece4a5eec0ccfa4d43b5af60acfecec55a53/site/src/github.rs#L43-L48 checks if the request contains "homu:", and if so passes it off to `handle_homu_res`. But handle_homu_res expects it to contain the string `<!-- homu: `: https://github.com/rust-lang/rustc-perf/blob/e8f5ece4a5eec0ccfa4d43b5af60acfecec55a53/site/src/github.rs#L550-L557
So anyone can crash rust-timer just by posting `Try build successful homu: x`.

**Comment by Mark-Simulacrum** [comment]
It'll restart automatically, and in any case I think only crashes the thread for that request -- IIRC, hyper automatically catches panics. So it's not really that bad.

Likely the easy fix is to verify the comment comes from bors (by github account id).

**Comment by jyn514** [comment]
> Likely the easy fix is to verify the comment comes from bors (by github account id).

I think it would be enough for the string to be the same, so they both check for "<!-- homu: ".

**Comment by Mark-Simulacrum** [comment]
Hm, it's likely not a good idea for us to listen in this particular case to other comments -- the intent is for only bors to communicate here. There's nothing really bad that can happen with someone else, I think, but it's better to limit ourselves to homu only.
