### ISSUE TITLE
A glossary of domain terms

### ISSUE THREAD

**Issue by rylev** [rust-lang/rustc-perf#938]
This is an attempt to give concrete terms to domain concepts that sometimes do not have set terminology within the codebase. If we can agree on these terms, we should move this glossary to the docs, and make sure the codebase consistently refers to these concepts using these terms. 

@wesleywiser and I devised this list in order to better be able to talk about how to model things within the codebase. 

# Proposal

## Basic terms

* **benchmark**: the source of a crate which will be used to benchmark rustc. For example, ["hello world"](https://github.com/rust-lang/rustc-perf/tree/master/collector/benchmarks/helloworld).
* **profile**: a [cargo profile](https://doc.rust-lang.org/cargo/reference/profiles.html). Note: the database uses "opt" whereas cargo uses "release". 
* **scenario**: The scenario under which a user is compiling their code. Currently, this is the incremental cache state and a change in the source since last compilation (e.g., adding a `println!` statement).  
* **metric**: a name of quantifiable statistic being measured (e.g., instruction count)
* **artifact**: a specific version of rustc (usually a commit sha or some sort of human readable "tag" like 1.51.0)

## Derived terms 
* **test case**: a combination of some benchmark, profile, and scenario.
* **test**: the act of running an artifact under a test case
* **test result**: the collection of all metrics as a result of a given artifact tested against a given test case. Each test result is composed of many iterations.
* **test iteration**: a single iteration that makes up a test case result. Note: we currently normal run 2 test iterations for each test. 
* **statistic**: a single value for a metric in a test case result
* **run**: a collection of test results for all currently available test cases run on a given artifact. Note: this term also means the process of collecting these test results.

**Comment by Mark-Simulacrum** [comment]
I think it's good to note somehow the self profile "attribute" (kinda a boolean), as well as document vocabulary for that data, it doesn't quite fit this existing terminology I think.

**Comment by rylev** [comment]
More terms:
* **stress test benchmark**: a benchmark that is specifically designed to stress a certain part of the compiler (e.g., [deeply-nested-async](https://github.com/rust-lang/rustc-perf/tree/master/collector/benchmarks/deeply-nested-async) is meant to stress parts of the compiler used in async code)
* **real world benchmark**: a benchmark based on a real world crate. These are typically copied as-is from crates.io. (e.g., [serde](https://github.com/rust-lang/rustc-perf/tree/master/collector/benchmarks/serde) is a popular crate and the benchmark has not been altered from a release of serde on crates.io). 
* **bootstrap**: the process of building the compiler from a previous version of the compiler
* **query**: a query used inside the [compiler query system](https://rustc-dev-guide.rust-lang.org/overview.html#queries).
* **noisy benchmark**: a benchmark that produces different (over some threshold) test results for multiple runs of the same test.
* **highly variable benchmark**: a benchmark that produces lots (over some threshold) of significant deltas between test results for different artifacts tested under the same test case.

**Comment by Mark-Simulacrum** [comment]
> highly variable benchmark: a benchmark that produces lots (over some threshold) of significant deltas between test results for different artifacts tested under the same test case.

Is this intended to mean "under not noop deltas" or something like that? IOW, the benchmark is highly *sensitive* perhaps would be more appropriate?

**Comment by rylev** [comment]
I believe what you're referring to is slightly different. Let me know how these look:
* **test result delta**: the delta between two test results for the same test case but (optionally) different artifacts. The [comparison page](https://perf.rust-lang.org/compare.html) lists many test result deltas as percentages.  
* **significant test result delta**: a test result delta that is above some threshold that we have determined to be an actual change in performance and not noise. 
* **highly sensitive benchmark**: a benchmark that tends to produce large (over some threshold) significant test result deltas. For example, some of the stress tests are highly sensitive; when they do produce significant test result deltas, the percentage change is typically quite large. 
* **highly variable benchmark**: a benchmark that frequently produces (over some threshold) significant test result deltas. This differs from sensitive benchmarks in that the deltas aren't necessarily large, they just happen more frequently than one would expect.  Note: highly variable benchmarks can be classified as noisy. They are different from classically noisy benchmarks in that they often have produce deltas that are above the significance threshold. We cannot therefore be 100% if they are variable because they are noisy or because parts of the compiler being exercised by these benchmarks are just being changed very often.

**Comment by Mark-Simulacrum** [comment]
I think I'm not yet sure what highly variable is intended to be used for. These are the variants (without choosing names for them) that I'm thinking about.

(Note: we seem to be missing a standard term for something like "a number shown on the page fully qualified, e.g. (cargo, opt, full, instructions:u). Here using the term Point + Point series [for the over time values of that specific number] for that, just to be quick- I'm not a fan of this name).

* Point series whose "significant" threshold (based on our current heuristic of x%ile over last N commits being exceeded?) is above our expectation of ~0.01%
  * useful to identify cases where we likely want to invest time in understanding why this is happening, and ideally reduce. Makes it hard to identify small improvements or regressions in the code exercised.
  * subset of this variant is a point series which shows different performance on seemingly "noop" commits - these are of particular concern.
* Point series highly tied to specific parts of the compiler. May not change often, but we know that the two are tightly connected. For example, incremental cases which currently skip CGU recompilation show enormous regressions if we no longer skip these regressions.
   * May be useful to know to identify strategies for interpretation & prevention. Likely means something different for the performance triage than a regular regression of 100%.

I think these match up closely with sensitive & highly variable but not sure if we're on the same page. My descriptions are definitely a little different from yours...

**Comment by rylev** [comment]
> I think I'm not yet sure what highly variable is intended to be used for.

We're [already using](https://github.com/rust-lang/rustc-perf/blob/b9fb9956fd7daebb60cfacfc4545f25dbe0f3585/site/src/comparison.rs#L593) this definition as a variant of noise. If a test case produces "significant" results very frequently it's hard to tell if that is because of legitimate changes to the compiler or simply because something in the testcase is extremely sensitive. We currently react to highly variable test cases the same as noisy ones, but this probably isn't right. 

(note:  in the comments above I wrote about noisy/highly variable benchmarks, but it's really test cases that are classified like this - sometimes certain benchmarks are noisy/highly variable with certain profile and scenario combinations.) 

> we seem to be missing a standard term for something like "a number shown on the page fully qualified, e.g. (cargo, opt, full, instructions:u

This is the term "statistic" (defined above) which is a single value for a given metric and test case. We could add "statistic series" as a specific term for that number over time. 

Your first definition seems to be exactly what I've defined as noisy plus some additional information of how we'd like to treat noise. I could add this to the definition, but it's not really part of its definition, just how we treat it. We should absolutely document this, but perhaps not in the glossary?

Your second definition seems to be exactly what I wrote about _highly sensitive_, just with the added example of CGU recompilation. Your added point about why this classification is useful is something we should document for sure, but I'm not sure it belongs in the glossary. 

Is there something we can change to the definitions of noisy and sensitive above that make it more clear what they refer to?

**Comment by Mark-Simulacrum** [comment]
> This is the term "statistic" (defined above) which is a single value for a given metric and test case. We could add "statistic series" as a specific term for that number over time.

Makes sense to me. I think I've just not yet internalized "test case" as including the scenario and such.

> If a test case produces "significant" results very frequently

I think this "very frequently" is what's bugging me. My understanding is that significant is currently derived as exceeding a threshold of historical deltas (for N past commits). That means that something that continues to produce significant results over time is oscillating with greater amplitude or growing/shrinking only on every commit, essentially, which seems unlikely to *ever* happen. My definition was intended to more precisely define this as the *significance* threshold for a given statistic being higher than we expect our statistics to have; I think we're on the same page as to what we want, just the wording is not quite clear in the description right now.

> Your first definition seems to be exactly what I've defined as noisy plus some additional information of how we'd like to treat noise. I could add this to the definition, but it's not really part of its definition, just how we treat it. We should absolutely document this, but perhaps not in the glossary?

Yes, seems good to not include the extra bits in the glossary. See my previous paragraph for details on what I think differs -- more clearly articulated today :)

> Your second definition seems to be exactly what I wrote about highly sensitive, just with the added example of CGU recompilation. Your added point about why this classification is useful is something we should document for sure, but I'm not sure it belongs in the glossary.

I think the additional bit is that a statistic is usually not well described by just being highly sensitive, it's the combination of statistic and "what it's sensitive to" (e.g., CGU recompilations in incremental is typical). A highly sensitive statistic to CGU recompilations should not be discounted *if no CGU recompilations occurred*, for example.

**Comment by rylev** [comment]
> the significance threshold for a given statistic being higher than we expect our statistics to have; I think we're on the same page as to what we want, just the wording is not quite clear in the description right now.

This is not how we currently define noisy (though it might be a better definition than we currently have). Currently we consider some arbitrary threshold significant (currently [0.1](https://github.com/rust-lang/rustc-perf/blob/2fa79d397da56e86633473b0ff5793ccd1f0a735/site/src/comparison.rs#L532)). All deltas that exceed that threshold are considered significant deltas. Highly variable test cases are ones which have more than [5%](https://github.com/rust-lang/rustc-perf/blob/2fa79d397da56e86633473b0ff5793ccd1f0a735/site/src/comparison.rs#L534) of their deltas that register as significant. Noisy test cases are those that have _non-significant_ deltas that on average are above [0.1%](https://github.com/rust-lang/rustc-perf/blob/master/site/src/comparison.rs#L536) changes - i.e., of all the deltas not big enough to be considered significant, do we still see a fairly large (arbitrarily set at 0.1% change) on average in these deltas. The thought is that for most test cases, there will be a few large changes which are significant and many changes that are very close to 0. Test cases that historically deviate from that pattern are considered noisy or highly variable depending on how they deviate. 

This is obviously not the most sophisticated and best way to capture and categorize noise, but it was chosen because it's fairly simple. I think we should document how noise is currently thought of in the system, and then in another change, we can adjust how we view noise (including making adjustments to its various definitions in the glossary). 

> a statistic is usually not well described by just being highly sensitive, it's the combination of statistic and "what it's sensitive to"

This makes a lot of sense! In turn highly variable test cases *might* be highly sensitive test cases for which we're just unaware of what the test case is sensitive too.

**Comment by Mark-Simulacrum** [comment]
> This is obviously not the most sophisticated and best way to capture and categorize noise, but it was chosen because it's fairly simple. I think we should document how noise is currently thought of in the system, and then in another change, we can adjust how we view noise (including making adjustments to its various definitions in the glossary).

Makes complete sense. I think there was a PR or issue or something talking about the more interesting version of defining noise... I recall some discussion. Anyway, for the current system, the definitions likely make sense; I think mine are a little more future proof but that doesn't seem necessary.

**Comment by rylev** [comment]
We now have a glossary after merging #942. Going to close this issue. We can open new issues  if we need to.
