### ISSUE TITLE
Bad data on the dashboard for 1.53

### ISSUE THREAD

**Issue by ecstatic-morse** [rust-lang/rustc-perf#947]
The data at https://perf.rust-lang.org/dashboard.html looks wrong for 1.53. Every benchmark flavor has a similar time to the `full` run for 1.52. The `beta` and `master` data looks more normal.

**Comment by bjorn3** [comment]
Incremental was disabled for 1.53, right? That matches this data perfectly. All incremental benchmarks take exactly as long as the non-incremental benchmarks.

**Comment by ecstatic-morse** [comment]
Ah, of course! I guess in retrospect we could have used `RUSTC_FORCE_INCREMENTAL` to keep things a little more consistent, but meh. Thanks!
