### ISSUE TITLE
Regression is described as both 'significant' and 'small'

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rustc-perf#968]
In https://github.com/rust-lang/rust/pull/87990#issuecomment-898203701, a 'small 0.3% regression' results in an overall description of a 'significant regression', and a corresponding 'perf-regression' label.

If 'significant regression' is referring to the magnitude of the regression, then this inconsistency should be fixed. If the message instead means something like 'statistically significant' or 'not due to noise', then the bot should leave a more descriptive comment.

**Comment by bjorn3** [comment]
That PR has a lot of smalish regressions. https://github.com/rust-lang/rustc-perf/pull/965 seems relevant.

**Comment by rylev** [comment]
The message is indeed a bit out of date. It originally meant "significant" as in "reasonably large", but #956 and #965 have adjusted how we're calculating whether a comparison is worth surfacing for attention. As is the case here, we can surface comparisons that include comparatively small deltas. We should update our messaging to better reflect this.

**Comment by rylev** [comment]
To be clear, I believe that the classifying of this particular comparison as a performance regression is correct. In turn, the [justification given](https://github.com/rust-lang/rust/pull/87990#issuecomment-899057176) for why the change should be merged anyway is also appropriate and correct. So overall, I think all that needs to be fixed here is the wording to make things clearer.
