### ISSUE TITLE
Website no longer supports filtering -doc runs only?

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rustc-perf#981]
I'm pretty sure I remember being able to filter for only rustdoc runs with a checkbox or something, but that checkbox is now gone. There's a text field that says "filter", but typing "doc" into it filters 100% of the benchmarks, including doc runs.

![Screenshot_20210822-074106](https://user-images.githubusercontent.com/23638587/130355553-7bd01a60-50ab-4cab-95bb-a3dbafab72e7.png)

**Comment by Mark-Simulacrum** [comment]
I think the profile isn't included in the substring search -doc would be a part of; -check etc don't work either.

**Comment by jyn514** [comment]
Sure, seems possible. It would be nice for it to be included again.

**Comment by Mark-Simulacrum** [comment]
I think this is broken (again?) -- I tried to filter by -check on https://perf.rust-lang.org/compare.html?start=e9f29a851917a706c01b6f51331894df1d15770b&end=63cc2bb3d07d6c726dfcdc5f95cbe5ed4760641a&stat=instructions:u, but that led to an empty page
