### ISSUE TITLE
Perf summaries ignore max-rss

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rustc-perf#988]
Max-rss has historically been noisy for rustc, but it's been quite accurate for rustdoc. https://github.com/rust-lang/rust/pull/88522#issuecomment-908912533 says "Summary: This benchmark run did not return any relevant changes.", but the max-rss measurement shows a consistent 1% improvement on -doc runs. It would be great for the summary to reflect that.

(This could be a duplicate of #980, but I suspect you went with just instruction count for the summaries while implementing the prototype.)

**Comment by Kobzol** [comment]
The PR summary comments now include Max RSS (and also cycles) in addition to instruction counts.
