### ISSUE TITLE
Perf bot should remove S-waiting-on-perf when a bors try build fails

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rustc-perf#994]
Since the PR author will have to update the PR before perf can benchmark it; e.g. https://github.com/rust-lang/rust/pull/88679#issuecomment-913274397

**Comment by Mark-Simulacrum** [comment]
Technically, the status *is* accurate -- the build remains queued even if the try build fails; we just wait for the first successful one. I definitely would prefer to avoid an additional comment left on the PR updating the state, so we'd want to work through the API (not rustbot).

**Comment by jyn514** [comment]
> Technically, the status is accurate -- the build remains queued even if the try build fails; we just wait for the first successful one.

TIL! What happens if you run `@rust-timer queue` when a PR is already queued, does it just do nothing?

> I definitely would prefer to avoid an additional comment left on the PR updating the state, so we'd want to work through the API (not rustbot).

:+1:

**Comment by Mark-Simulacrum** [comment]
Yes, it's a noop if the PR is already "looking for try build".

**Comment by rylev** [comment]
Should this issue be closed then?

**Comment by Mark-Simulacrum** [comment]
I think so. Going to go ahead and close it.
