### ISSUE TITLE
Remove the absolute test result numbers from the comparison page

### ISSUE THREAD

**Issue by rylev** [rust-lang/rustc-perf#998]
The comparison page provides two columns with the absolute numbers (in milliseconds?) of the two artifacts being compared. I never look at these numbers since it's only important what the difference between them is. Perhaps these can be removed and more useful data (e.g., the severity number proposed in #997) could be used instead. 

![image](https://user-images.githubusercontent.com/1327285/132875231-e6f2ed8a-78cf-4363-9838-62658126a3b0.png)

**Comment by Mark-Simulacrum** [comment]
These columns are *really* useful when looking at non-instruction count views. For instruction counts, they're not particularly useful (mostly because they're so large and unwieldy). But e.g. task-clock - it can be helpful to know whether the benchmark takes 0.1 seconds to run or 20.

**Comment by rylev** [comment]
Good point. Do you ever spend time scanning these numbers or do you usually look at the percent change and then check for the scale of the numbers? These numbers take up a lot of screen real-estate so it's good to check if we could potentially save space by moving them to a secondary view (e.g., on hover).

**Comment by Mark-Simulacrum** [comment]
I think we can definitely trim to less decimal places (e.g., 2 is probably more than our precision would allow anyway), which would help.

I scan the numbers directly sometimes when trying to scan 'are all these tiny benchmarks' -- IOW, is the magnitude of the change attributable in part to a small baseline. I think that can be exposed across all views with some other kind of indicator (e.g., a column for 'rough benchmark magnitude' with just M1/2/3 and some arbitrary-ish groupings for those).
